// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCX version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': 'src/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'sycl_defines': True,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['problem.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

ufc_finite_element* create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686(void);

ufc_finite_element* create_element_445ef1924184cca3ac2920e3df00b14f41104dec(void);

ufc_finite_element* create_element_428b642cdbd29d9b27503f3b645dc2918edc7850(void);

ufc_dofmap* create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686(void);

ufc_dofmap* create_dofmap_445ef1924184cca3ac2920e3df00b14f41104dec(void);

ufc_dofmap* create_dofmap_428b642cdbd29d9b27503f3b645dc2918edc7850(void);

ufc_coordinate_mapping* create_coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd(void);

// Helper used to create coordinate map using name given to the
// UFL file.
// This helper is called in user c++ code.
//
ufc_coordinate_mapping* create_coordinate_map_problem(void);

ufc_integral* create_integral_cell_otherwise_726e602d497be77b561b62144fa710a5219a470c(void);

ufc_integral* create_integral_cell_otherwise_d7784bb426acb67ec050072a6ec8e2234c9eb501(void);

ufc_form* create_form_726e602d497be77b561b62144fa710a5219a470c(void);

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
ufc_form* create_form_problem_a(void);

// Helper used to create function space using its name, as given in
// the UFL file.
// Note: There are in general more function spaces associated to the form,
//       which is the reason why the helpers takes name as argument.
// This helper is called in user c++ code.
//
ufc_function_space* create_functionspace_form_problem_a(const char* fs_name);


ufc_form* create_form_d7784bb426acb67ec050072a6ec8e2234c9eb501(void);

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
ufc_form* create_form_problem_L(void);

// Helper used to create function space using its name, as given in
// the UFL file.
// Note: There are in general more function spaces associated to the form,
//       which is the reason why the helpers takes name as argument.
// This helper is called in user c++ code.
//
ufc_function_space* create_functionspace_form_problem_L(const char* fs_name);


#ifdef __cplusplus
}
#endif
