// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.1.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': 'src/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['problem.ufl'],
//   'verbosity': 30,
//   'visualise': False}


typedef double ufc_scalar_t;
#include <math.h>
#include <stdalign.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <ufc.h>

// Code for element element_f6052a0d9b38897ec9c4756c9defe0eb11408116





ufc_finite_element element_f6052a0d9b38897ec9c4756c9defe0eb11408116 =
{
  .signature = "FiniteElement('Lagrange', tetrahedron, 1)",
  .cell_shape = tetrahedron,
  .element_type = ufc_basix_element,
  .topological_dimension = 3,
  .geometric_dimension = 3,
  .space_dimension = 4,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .family = "Lagrange",
  .block_size = 1,

  .num_sub_elements = 0,
  .sub_elements = NULL
};

// End of code for element element_f6052a0d9b38897ec9c4756c9defe0eb11408116

// Code for element element_7e3ab6fd41e2ad17e75e5246b6b9abd2ed1cc400

int value_shape_element_7e3ab6fd41e2ad17e75e5246b6b9abd2ed1cc400[1] = { 3 };
int reference_value_shape_element_7e3ab6fd41e2ad17e75e5246b6b9abd2ed1cc400[1] = { 3 };
ufc_finite_element* sub_elements_element_7e3ab6fd41e2ad17e75e5246b6b9abd2ed1cc400[3] = { &element_f6052a0d9b38897ec9c4756c9defe0eb11408116, &element_f6052a0d9b38897ec9c4756c9defe0eb11408116, &element_f6052a0d9b38897ec9c4756c9defe0eb11408116 };

ufc_finite_element element_7e3ab6fd41e2ad17e75e5246b6b9abd2ed1cc400 =
{
  .signature = "VectorElement(FiniteElement('Lagrange', tetrahedron, 1), dim=3)",
  .cell_shape = tetrahedron,
  .element_type = ufc_blocked_element,
  .topological_dimension = 3,
  .geometric_dimension = 3,
  .space_dimension = 12,
  .value_rank = 1,
  .value_shape = value_shape_element_7e3ab6fd41e2ad17e75e5246b6b9abd2ed1cc400,
  .value_size = 3,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_7e3ab6fd41e2ad17e75e5246b6b9abd2ed1cc400,
  .reference_value_size = 3,
  .degree = 1,
  .family = "Lagrange",
  .block_size = 3,

  .num_sub_elements = 3,
  .sub_elements = sub_elements_element_7e3ab6fd41e2ad17e75e5246b6b9abd2ed1cc400
};

// End of code for element element_7e3ab6fd41e2ad17e75e5246b6b9abd2ed1cc400

// Code for element element_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b





ufc_finite_element element_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b =
{
  .signature = "FiniteElement('Lagrange', tetrahedron, 2)",
  .cell_shape = tetrahedron,
  .element_type = ufc_basix_element,
  .topological_dimension = 3,
  .geometric_dimension = 3,
  .space_dimension = 10,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 2,
  .family = "Lagrange",
  .block_size = 1,

  .num_sub_elements = 0,
  .sub_elements = NULL
};

// End of code for element element_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b

// Code for dofmap dofmap_f6052a0d9b38897ec9c4756c9defe0eb11408116



void tabulate_entity_dofs_dofmap_f6052a0d9b38897ec9c4756c9defe0eb11408116(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
}
}

ufc_dofmap dofmap_f6052a0d9b38897ec9c4756c9defe0eb11408116 =
{
  .signature = "FFCx dofmap for FiniteElement('Lagrange', tetrahedron, 1)",
  .block_size = 1,
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 4,
  .num_entity_dofs[0] = 1,
  .num_entity_dofs[1] = 0,
  .num_entity_dofs[2] = 0,
  .num_entity_dofs[3] = 0,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_f6052a0d9b38897ec9c4756c9defe0eb11408116,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_f6052a0d9b38897ec9c4756c9defe0eb11408116

// Code for dofmap dofmap_7e3ab6fd41e2ad17e75e5246b6b9abd2ed1cc400

ufc_dofmap* sub_dofmaps_dofmap_7e3ab6fd41e2ad17e75e5246b6b9abd2ed1cc400[3] = { &dofmap_f6052a0d9b38897ec9c4756c9defe0eb11408116, &dofmap_f6052a0d9b38897ec9c4756c9defe0eb11408116, &dofmap_f6052a0d9b38897ec9c4756c9defe0eb11408116 };

void tabulate_entity_dofs_dofmap_7e3ab6fd41e2ad17e75e5246b6b9abd2ed1cc400(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
}
}

ufc_dofmap dofmap_7e3ab6fd41e2ad17e75e5246b6b9abd2ed1cc400 =
{
  .signature = "FFCx dofmap for VectorElement(FiniteElement('Lagrange', tetrahedron, 1), dim=3)",
  .block_size = 3,
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 4,
  .num_entity_dofs[0] = 1,
  .num_entity_dofs[1] = 0,
  .num_entity_dofs[2] = 0,
  .num_entity_dofs[3] = 0,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_7e3ab6fd41e2ad17e75e5246b6b9abd2ed1cc400,
  .num_sub_dofmaps = 3,
  .sub_dofmaps = sub_dofmaps_dofmap_7e3ab6fd41e2ad17e75e5246b6b9abd2ed1cc400
};

// End of code for dofmap dofmap_7e3ab6fd41e2ad17e75e5246b6b9abd2ed1cc400

// Code for dofmap dofmap_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b



void tabulate_entity_dofs_dofmap_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
case 1:
    switch (i)
    {
    case 0:
        dofs[0] = 4;
        break;
    case 1:
        dofs[0] = 5;
        break;
    case 2:
        dofs[0] = 6;
        break;
    case 3:
        dofs[0] = 7;
        break;
    case 4:
        dofs[0] = 8;
        break;
    case 5:
        dofs[0] = 9;
        break;
    }
    break;
}
}

ufc_dofmap dofmap_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b =
{
  .signature = "FFCx dofmap for FiniteElement('Lagrange', tetrahedron, 2)",
  .block_size = 1,
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 10,
  .num_entity_dofs[0] = 1,
  .num_entity_dofs[1] = 1,
  .num_entity_dofs[2] = 0,
  .num_entity_dofs[3] = 0,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b

// Code for integral integral_69d4cbc67251de8d7f3cd107fabff52c17b0f328

void tabulate_tensor_integral_69d4cbc67251de8d7f3cd107fabff52c17b0f328(ufc_scalar_t* restrict A,
                                    const ufc_scalar_t* restrict w,
                                    const ufc_scalar_t* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
    // Quadrature rules
    static const double weights_d8a[14] = { 0.003174603174603167, 0.003174603174603167, 0.003174603174603167, 0.003174603174603167, 0.003174603174603167, 0.003174603174603167, 0.01476497079049678, 0.01476497079049678, 0.01476497079049678, 0.01476497079049678, 0.02213979111426512, 0.02213979111426512, 0.02213979111426512, 0.02213979111426512 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE17_C0_D001_Qd8a[1][1][14][10] =
        { { { { 1.0, 0.0, 0.0, 1.0, 2.0, 0.0, 0.0, -2.0, -2.0, 0.0 },
              { 1.0, 0.0, 0.0, 1.0, 0.0, 2.0, 0.0, -2.0, 0.0, -2.0 },
              { 1.0, 0.0, 0.0, -1.0, 2.0, 2.0, 0.0, 0.0, -2.0, -1.999999999999999 },
              { -1.0, 0.0, 0.0, -1.0, 0.0, 2.0, 0.0, 2.0, 0.0, -2.0 },
              { -1.0, 0.0, 0.0, -1.0, 2.0, 0.0, 0.0, 2.0, -2.0, 0.0 },
              { -1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.5978929390991826, 0.0, 0.0, -0.5978929390991822, 0.4021070609008178, 2.793678817297546, 0.0, 0.0, -0.402107060900818, -2.793678817297546 },
              { -1.793678817297546, 0.0, 0.0, -0.5978929390991821, 0.4021070609008178, 0.4021070609008177, 0.0, 2.391571756396728, -0.4021070609008181, -0.4021070609008178 },
              { 0.5978929390991823, 0.0, 0.0, 1.793678817297546, 0.402107060900818, 0.4021070609008179, 0.0, -2.391571756396728, -0.4021070609008179, -0.4021070609008178 },
              { 0.597892939099182, 0.0, 0.0, -0.5978929390991823, 2.793678817297546, 0.4021070609008187, 0.0, 0.0, -2.793678817297546, -0.4021070609008173 },
              { -0.2574914939727688, 0.0, 0.0, 0.2574914939727688, 1.257491493972769, 0.2275255180816937, 0.0, 0.0, -1.257491493972769, -0.2275255180816933 },
              { 0.7724744819183066, 0.0, 0.0, 0.2574914939727688, 1.257491493972769, 1.257491493972769, 0.0, -1.029965975891075, -1.257491493972768, -1.257491493972768 },
              { -0.2574914939727687, 0.0, 0.0, -0.7724744819183067, 1.257491493972769, 1.257491493972769, 0.0, 1.029965975891076, -1.257491493972769, -1.257491493972768 },
              { -0.2574914939727686, 0.0, 0.0, 0.2574914939727688, 0.2275255180816938, 1.257491493972769, 0.0, 0.0, -0.2275255180816936, -1.257491493972769 } } } };
    static const double FE17_C0_D010_Qd8a[1][1][14][10] =
        { { { { 1.0, 0.0, 1.0, 0.0, 2.0, 0.0, 0.0, -2.0, -2.0, 0.0 },
              { 1.0, 0.0, -1.0, 0.0, 2.0, 0.0, 2.0, -2.0, 0.0, -2.0 },
              { 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 2.0, 0.0, -2.0, -1.999999999999999 },
              { -1.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.999999999999999, 0.0, 2.0, -2.0 },
              { -1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { -1.0, 0.0, -1.0, 0.0, 1.999999999999999, 0.0, 0.0, -2.0, 2.0, 0.0 },
              { 0.5978929390991826, 0.0, -0.5978929390991822, 0.0, 0.402107060900818, 0.0, 2.793678817297546, -0.4021070609008177, 0.0, -2.793678817297546 },
              { -1.793678817297546, 0.0, -0.597892939099182, 0.0, 0.4021070609008174, 0.0, 0.4021070609008172, -0.4021070609008186, 2.391571756396728, -0.4021070609008183 },
              { 0.5978929390991823, 0.0, -0.597892939099182, 0.0, 2.793678817297546, 0.0, 0.4021070609008178, -2.793678817297546, 0.0, -0.4021070609008177 },
              { 0.597892939099182, 0.0, 1.793678817297546, 0.0, 0.4021070609008187, 0.0, 0.4021070609008182, -0.4021070609008175, -2.391571756396728, -0.4021070609008172 },
              { -0.2574914939727687, 0.0, 0.2574914939727688, 0.0, 1.257491493972769, 0.0, 0.2275255180816936, -1.257491493972769, 0.0, -0.2275255180816935 },
              { 0.7724744819183066, 0.0, 0.2574914939727687, 0.0, 1.257491493972769, 0.0, 1.257491493972769, -1.257491493972768, -1.029965975891075, -1.257491493972768 },
              { -0.2574914939727687, 0.0, 0.2574914939727687, 0.0, 0.2275255180816935, 0.0, 1.257491493972769, -0.2275255180816935, 0.0, -1.257491493972768 },
              { -0.2574914939727685, 0.0, -0.7724744819183064, 0.0, 1.257491493972768, 0.0, 1.257491493972768, -1.257491493972769, 1.029965975891075, -1.257491493972769 } } } };
    static const double FE17_C0_D100_Qd8a[1][1][14][10] =
        { { { { 1.0, -1.0, 0.0, 0.0, 0.0, 2.0, 2.0, -2.0, -2.0, 0.0 },
              { 1.0, 1.0, 0.0, 0.0, 0.0, 2.0, 0.0, -2.0, 0.0, -2.0 },
              { 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, -2.0, -2.0 },
              { -1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, -2.0, 2.0 },
              { -1.0, -1.0, 0.0, 0.0, 0.0, 2.0, 0.0, -2.0, 0.0, 2.0 },
              { 0.5978929390991826, 1.793678817297547, 0.0, 0.0, 0.0, 0.4021070609008178, 0.4021070609008179, -0.4021070609008178, -0.4021070609008179, -2.391571756396729 },
              { -1.793678817297546, -0.5978929390991824, 0.0, 0.0, 0.0, 0.402107060900818, 0.4021070609008177, -0.4021070609008183, -0.4021070609008179, 2.391571756396728 },
              { 0.5978929390991825, -0.5978929390991824, 0.0, 0.0, 0.0, 2.793678817297546, 0.4021070609008179, -2.793678817297546, -0.4021070609008179, 0.0 },
              { 0.597892939099182, -0.5978929390991824, 0.0, 0.0, 0.0, 0.4021070609008185, 2.793678817297546, -0.4021070609008174, -2.793678817297546, 0.0 },
              { -0.2574914939727687, -0.7724744819183068, 0.0, 0.0, 0.0, 1.257491493972769, 1.257491493972769, -1.257491493972769, -1.257491493972769, 1.029965975891076 },
              { 0.7724744819183068, 0.2574914939727687, 0.0, 0.0, 0.0, 1.257491493972769, 1.257491493972769, -1.257491493972768, -1.257491493972769, -1.029965975891075 },
              { -0.2574914939727687, 0.2574914939727687, 0.0, 0.0, 0.0, 0.2275255180816938, 1.257491493972769, -0.2275255180816935, -1.257491493972769, 0.0 },
              { -0.2574914939727686, 0.2574914939727687, 0.0, 0.0, 0.0, 1.257491493972769, 0.2275255180816935, -1.257491493972769, -0.2275255180816936, 0.0 } } } };
    static const double FE17_C0_Qd8a[1][1][14][10] =
        { { { { 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0 },
              { -0.08031550417191767, 0.2771604624527406, -0.08031550417191774, -0.0803155041719177, 0.04042252210657353, 0.2808394945810975, 0.2808394945810974, 0.04042252210657353, 0.04042252210657352, 0.2808394945810972 },
              { 0.2771604624527404, -0.08031550417191773, -0.08031550417191774, -0.08031550417191767, 0.04042252210657356, 0.04042252210657357, 0.04042252210657356, 0.2808394945810975, 0.2808394945810974, 0.2808394945810972 },
              { -0.08031550417191774, -0.08031550417191774, -0.08031550417191774, 0.2771604624527406, 0.2808394945810976, 0.2808394945810974, 0.0404225221065735, 0.2808394945810974, 0.0404225221065735, 0.04042252210657347 },
              { -0.08031550417191775, -0.08031550417191773, 0.2771604624527405, -0.08031550417191768, 0.2808394945810975, 0.04042252210657358, 0.2808394945810973, 0.04042252210657355, 0.2808394945810972, 0.0404225221065735 },
              { -0.116712266316459, -0.05041039684813046, -0.1167122663164589, -0.1167122663164589, 0.3953212143534666, 0.07152785091236924, 0.07152785091236921, 0.3953212143534666, 0.3953212143534665, 0.07152785091236913 },
              { -0.05041039684813049, -0.116712266316459, -0.1167122663164589, -0.1167122663164589, 0.3953212143534666, 0.3953212143534666, 0.3953212143534665, 0.07152785091236931, 0.07152785091236924, 0.07152785091236924 },
              { -0.116712266316459, -0.116712266316459, -0.116712266316459, -0.05041039684813045, 0.07152785091236921, 0.07152785091236924, 0.3953212143534665, 0.07152785091236924, 0.3953212143534665, 0.3953212143534665 },
              { -0.116712266316459, -0.116712266316459, -0.05041039684813052, -0.1167122663164589, 0.07152785091236936, 0.3953212143534666, 0.07152785091236927, 0.3953212143534666, 0.07152785091236927, 0.3953212143534665 } } } };
    static const double FE9_C0_D100_Qd8a[1][1][1][4] = { { { { -1.0, 1.0, 0.0, 0.0 } } } };
    static const double FE9_C1_D010_Qd8a[1][1][1][4] = { { { { -1.0, 0.0, 1.0, 0.0 } } } };
    static const double FE9_C2_D001_Qd8a[1][1][1][4] = { { { { -1.0, 0.0, 0.0, 1.0 } } } };
    // Quadrature loop independent computations for quadrature rule d8a
    const double J_c4 = coordinate_dofs[1] * FE9_C1_D010_Qd8a[0][0][0][0] + coordinate_dofs[4] * FE9_C1_D010_Qd8a[0][0][0][1] + coordinate_dofs[7] * FE9_C1_D010_Qd8a[0][0][0][2] + coordinate_dofs[10] * FE9_C1_D010_Qd8a[0][0][0][3];
    const double J_c8 = coordinate_dofs[2] * FE9_C2_D001_Qd8a[0][0][0][0] + coordinate_dofs[5] * FE9_C2_D001_Qd8a[0][0][0][1] + coordinate_dofs[8] * FE9_C2_D001_Qd8a[0][0][0][2] + coordinate_dofs[11] * FE9_C2_D001_Qd8a[0][0][0][3];
    const double J_c5 = coordinate_dofs[1] * FE9_C2_D001_Qd8a[0][0][0][0] + coordinate_dofs[4] * FE9_C2_D001_Qd8a[0][0][0][1] + coordinate_dofs[7] * FE9_C2_D001_Qd8a[0][0][0][2] + coordinate_dofs[10] * FE9_C2_D001_Qd8a[0][0][0][3];
    const double J_c7 = coordinate_dofs[2] * FE9_C1_D010_Qd8a[0][0][0][0] + coordinate_dofs[5] * FE9_C1_D010_Qd8a[0][0][0][1] + coordinate_dofs[8] * FE9_C1_D010_Qd8a[0][0][0][2] + coordinate_dofs[11] * FE9_C1_D010_Qd8a[0][0][0][3];
    const double J_c0 = coordinate_dofs[0] * FE9_C0_D100_Qd8a[0][0][0][0] + coordinate_dofs[3] * FE9_C0_D100_Qd8a[0][0][0][1] + coordinate_dofs[6] * FE9_C0_D100_Qd8a[0][0][0][2] + coordinate_dofs[9] * FE9_C0_D100_Qd8a[0][0][0][3];
    const double J_c1 = coordinate_dofs[0] * FE9_C1_D010_Qd8a[0][0][0][0] + coordinate_dofs[3] * FE9_C1_D010_Qd8a[0][0][0][1] + coordinate_dofs[6] * FE9_C1_D010_Qd8a[0][0][0][2] + coordinate_dofs[9] * FE9_C1_D010_Qd8a[0][0][0][3];
    const double J_c6 = coordinate_dofs[2] * FE9_C0_D100_Qd8a[0][0][0][0] + coordinate_dofs[5] * FE9_C0_D100_Qd8a[0][0][0][1] + coordinate_dofs[8] * FE9_C0_D100_Qd8a[0][0][0][2] + coordinate_dofs[11] * FE9_C0_D100_Qd8a[0][0][0][3];
    const double J_c3 = coordinate_dofs[1] * FE9_C0_D100_Qd8a[0][0][0][0] + coordinate_dofs[4] * FE9_C0_D100_Qd8a[0][0][0][1] + coordinate_dofs[7] * FE9_C0_D100_Qd8a[0][0][0][2] + coordinate_dofs[10] * FE9_C0_D100_Qd8a[0][0][0][3];
    const double J_c2 = coordinate_dofs[0] * FE9_C2_D001_Qd8a[0][0][0][0] + coordinate_dofs[3] * FE9_C2_D001_Qd8a[0][0][0][1] + coordinate_dofs[6] * FE9_C2_D001_Qd8a[0][0][0][2] + coordinate_dofs[9] * FE9_C2_D001_Qd8a[0][0][0][3];
    ufc_scalar_t sp_d8a[80];
    sp_d8a[0] = J_c4 * J_c8;
    sp_d8a[1] = J_c5 * J_c7;
    sp_d8a[2] = sp_d8a[0] + -1 * sp_d8a[1];
    sp_d8a[3] = J_c0 * sp_d8a[2];
    sp_d8a[4] = J_c5 * J_c6;
    sp_d8a[5] = J_c3 * J_c8;
    sp_d8a[6] = sp_d8a[4] + -1 * sp_d8a[5];
    sp_d8a[7] = J_c1 * sp_d8a[6];
    sp_d8a[8] = sp_d8a[3] + sp_d8a[7];
    sp_d8a[9] = J_c3 * J_c7;
    sp_d8a[10] = J_c4 * J_c6;
    sp_d8a[11] = sp_d8a[9] + -1 * sp_d8a[10];
    sp_d8a[12] = J_c2 * sp_d8a[11];
    sp_d8a[13] = sp_d8a[8] + sp_d8a[12];
    sp_d8a[14] = sp_d8a[2] / sp_d8a[13];
    sp_d8a[15] = J_c3 * (-1 * J_c8);
    sp_d8a[16] = sp_d8a[4] + sp_d8a[15];
    sp_d8a[17] = sp_d8a[16] / sp_d8a[13];
    sp_d8a[18] = sp_d8a[11] / sp_d8a[13];
    sp_d8a[19] = sp_d8a[14] * sp_d8a[14];
    sp_d8a[20] = sp_d8a[14] * sp_d8a[17];
    sp_d8a[21] = sp_d8a[18] * sp_d8a[14];
    sp_d8a[22] = sp_d8a[17] * sp_d8a[17];
    sp_d8a[23] = sp_d8a[18] * sp_d8a[17];
    sp_d8a[24] = sp_d8a[18] * sp_d8a[18];
    sp_d8a[25] = J_c2 * J_c7;
    sp_d8a[26] = J_c8 * (-1 * J_c1);
    sp_d8a[27] = sp_d8a[25] + sp_d8a[26];
    sp_d8a[28] = sp_d8a[27] / sp_d8a[13];
    sp_d8a[29] = J_c0 * J_c8;
    sp_d8a[30] = J_c6 * (-1 * J_c2);
    sp_d8a[31] = sp_d8a[29] + sp_d8a[30];
    sp_d8a[32] = sp_d8a[31] / sp_d8a[13];
    sp_d8a[33] = J_c1 * J_c6;
    sp_d8a[34] = J_c0 * J_c7;
    sp_d8a[35] = sp_d8a[33] + -1 * sp_d8a[34];
    sp_d8a[36] = sp_d8a[35] / sp_d8a[13];
    sp_d8a[37] = sp_d8a[28] * sp_d8a[28];
    sp_d8a[38] = sp_d8a[28] * sp_d8a[32];
    sp_d8a[39] = sp_d8a[28] * sp_d8a[36];
    sp_d8a[40] = sp_d8a[32] * sp_d8a[32];
    sp_d8a[41] = sp_d8a[32] * sp_d8a[36];
    sp_d8a[42] = sp_d8a[36] * sp_d8a[36];
    sp_d8a[43] = sp_d8a[37] + sp_d8a[19];
    sp_d8a[44] = sp_d8a[38] + sp_d8a[20];
    sp_d8a[45] = sp_d8a[39] + sp_d8a[21];
    sp_d8a[46] = sp_d8a[40] + sp_d8a[22];
    sp_d8a[47] = sp_d8a[41] + sp_d8a[23];
    sp_d8a[48] = sp_d8a[24] + sp_d8a[42];
    sp_d8a[49] = J_c1 * J_c5;
    sp_d8a[50] = J_c2 * J_c4;
    sp_d8a[51] = sp_d8a[49] + -1 * sp_d8a[50];
    sp_d8a[52] = sp_d8a[51] / sp_d8a[13];
    sp_d8a[53] = J_c2 * J_c3;
    sp_d8a[54] = J_c0 * J_c5;
    sp_d8a[55] = sp_d8a[53] + -1 * sp_d8a[54];
    sp_d8a[56] = sp_d8a[55] / sp_d8a[13];
    sp_d8a[57] = J_c0 * J_c4;
    sp_d8a[58] = J_c1 * J_c3;
    sp_d8a[59] = sp_d8a[57] + -1 * sp_d8a[58];
    sp_d8a[60] = sp_d8a[59] / sp_d8a[13];
    sp_d8a[61] = sp_d8a[52] * sp_d8a[52];
    sp_d8a[62] = sp_d8a[52] * sp_d8a[56];
    sp_d8a[63] = sp_d8a[60] * sp_d8a[52];
    sp_d8a[64] = sp_d8a[56] * sp_d8a[56];
    sp_d8a[65] = sp_d8a[60] * sp_d8a[56];
    sp_d8a[66] = sp_d8a[60] * sp_d8a[60];
    sp_d8a[67] = sp_d8a[43] + sp_d8a[61];
    sp_d8a[68] = sp_d8a[44] + sp_d8a[62];
    sp_d8a[69] = sp_d8a[45] + sp_d8a[63];
    sp_d8a[70] = sp_d8a[46] + sp_d8a[64];
    sp_d8a[71] = sp_d8a[47] + sp_d8a[65];
    sp_d8a[72] = sp_d8a[48] + sp_d8a[66];
    sp_d8a[73] = fabs(sp_d8a[13]);
    sp_d8a[74] = sp_d8a[67] * sp_d8a[73];
    sp_d8a[75] = sp_d8a[68] * sp_d8a[73];
    sp_d8a[76] = sp_d8a[69] * sp_d8a[73];
    sp_d8a[77] = sp_d8a[70] * sp_d8a[73];
    sp_d8a[78] = sp_d8a[71] * sp_d8a[73];
    sp_d8a[79] = sp_d8a[72] * sp_d8a[73];
    for (int iq = 0; iq < 14; ++iq)
    {
        const ufc_scalar_t fw0 = sp_d8a[73] * weights_d8a[iq];
        const ufc_scalar_t fw1 = sp_d8a[74] * weights_d8a[iq];
        const ufc_scalar_t fw2 = sp_d8a[75] * weights_d8a[iq];
        const ufc_scalar_t fw3 = sp_d8a[76] * weights_d8a[iq];
        const ufc_scalar_t fw4 = sp_d8a[77] * weights_d8a[iq];
        const ufc_scalar_t fw5 = sp_d8a[78] * weights_d8a[iq];
        const ufc_scalar_t fw6 = sp_d8a[79] * weights_d8a[iq];
        ufc_scalar_t t0[10];
        ufc_scalar_t t1[10];
        ufc_scalar_t t2[10];
        ufc_scalar_t t3[10];
        for (int i = 0; i < 10; ++i)
        {
            t0[i] = fw0 * FE17_C0_Qd8a[0][0][iq][i];
            t1[i] = fw1 * FE17_C0_D100_Qd8a[0][0][iq][i] + fw2 * FE17_C0_D010_Qd8a[0][0][iq][i] + fw3 * FE17_C0_D001_Qd8a[0][0][iq][i];
            t2[i] = fw2 * FE17_C0_D100_Qd8a[0][0][iq][i] + fw4 * FE17_C0_D010_Qd8a[0][0][iq][i] + fw5 * FE17_C0_D001_Qd8a[0][0][iq][i];
            t3[i] = fw3 * FE17_C0_D100_Qd8a[0][0][iq][i] + fw5 * FE17_C0_D010_Qd8a[0][0][iq][i] + fw6 * FE17_C0_D001_Qd8a[0][0][iq][i];
        }
        for (int i = 0; i < 10; ++i)
        {
            for (int j = 0; j < 10; ++j)
            {
                ufc_scalar_t acc0 = 0;
                acc0 += FE17_C0_Qd8a[0][0][iq][j] * t0[i];
                acc0 += FE17_C0_D100_Qd8a[0][0][iq][j] * t1[i];
                acc0 += FE17_C0_D010_Qd8a[0][0][iq][j] * t2[i];
                acc0 += FE17_C0_D001_Qd8a[0][0][iq][j] * t3[i];
                A[10 * i + j] += acc0;
            }
        }
    }
}



ufc_integral integral_69d4cbc67251de8d7f3cd107fabff52c17b0f328 =
{
  .enabled_coefficients = NULL,
  .tabulate_tensor = tabulate_tensor_integral_69d4cbc67251de8d7f3cd107fabff52c17b0f328,
};

// End of code for integral integral_69d4cbc67251de8d7f3cd107fabff52c17b0f328

// Code for integral integral_2ae982a7fa3a191994f76b9ba8ae636a646a265a

void tabulate_tensor_integral_2ae982a7fa3a191994f76b9ba8ae636a646a265a(ufc_scalar_t* restrict A,
                                    const ufc_scalar_t* restrict w,
                                    const ufc_scalar_t* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
    // Quadrature rules
    static const double weights_d8a[14] = { 0.003174603174603167, 0.003174603174603167, 0.003174603174603167, 0.003174603174603167, 0.003174603174603167, 0.003174603174603167, 0.01476497079049678, 0.01476497079049678, 0.01476497079049678, 0.01476497079049678, 0.02213979111426512, 0.02213979111426512, 0.02213979111426512, 0.02213979111426512 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE11_C0_Qd8a[1][1][14][10] =
        { { { { 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0 },
              { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0 },
              { -0.08031550417191767, 0.2771604624527406, -0.08031550417191774, -0.0803155041719177, 0.04042252210657353, 0.2808394945810975, 0.2808394945810974, 0.04042252210657353, 0.04042252210657352, 0.2808394945810972 },
              { 0.2771604624527404, -0.08031550417191773, -0.08031550417191774, -0.08031550417191767, 0.04042252210657356, 0.04042252210657357, 0.04042252210657356, 0.2808394945810975, 0.2808394945810974, 0.2808394945810972 },
              { -0.08031550417191774, -0.08031550417191774, -0.08031550417191774, 0.2771604624527406, 0.2808394945810976, 0.2808394945810974, 0.0404225221065735, 0.2808394945810974, 0.0404225221065735, 0.04042252210657347 },
              { -0.08031550417191775, -0.08031550417191773, 0.2771604624527405, -0.08031550417191768, 0.2808394945810975, 0.04042252210657358, 0.2808394945810973, 0.04042252210657355, 0.2808394945810972, 0.0404225221065735 },
              { -0.116712266316459, -0.05041039684813046, -0.1167122663164589, -0.1167122663164589, 0.3953212143534666, 0.07152785091236924, 0.07152785091236921, 0.3953212143534666, 0.3953212143534665, 0.07152785091236913 },
              { -0.05041039684813049, -0.116712266316459, -0.1167122663164589, -0.1167122663164589, 0.3953212143534666, 0.3953212143534666, 0.3953212143534665, 0.07152785091236931, 0.07152785091236924, 0.07152785091236924 },
              { -0.116712266316459, -0.116712266316459, -0.116712266316459, -0.05041039684813045, 0.07152785091236921, 0.07152785091236924, 0.3953212143534665, 0.07152785091236924, 0.3953212143534665, 0.3953212143534665 },
              { -0.116712266316459, -0.116712266316459, -0.05041039684813052, -0.1167122663164589, 0.07152785091236936, 0.3953212143534666, 0.07152785091236927, 0.3953212143534666, 0.07152785091236927, 0.3953212143534665 } } } };
    static const double FE9_C0_D100_Qd8a[1][1][1][4] = { { { { -1.0, 1.0, 0.0, 0.0 } } } };
    static const double FE9_C1_D010_Qd8a[1][1][1][4] = { { { { -1.0, 0.0, 1.0, 0.0 } } } };
    static const double FE9_C2_D001_Qd8a[1][1][1][4] = { { { { -1.0, 0.0, 0.0, 1.0 } } } };
    // Quadrature loop independent computations for quadrature rule d8a
    const double J_c0 = coordinate_dofs[0] * FE9_C0_D100_Qd8a[0][0][0][0] + coordinate_dofs[3] * FE9_C0_D100_Qd8a[0][0][0][1] + coordinate_dofs[6] * FE9_C0_D100_Qd8a[0][0][0][2] + coordinate_dofs[9] * FE9_C0_D100_Qd8a[0][0][0][3];
    const double J_c4 = coordinate_dofs[1] * FE9_C1_D010_Qd8a[0][0][0][0] + coordinate_dofs[4] * FE9_C1_D010_Qd8a[0][0][0][1] + coordinate_dofs[7] * FE9_C1_D010_Qd8a[0][0][0][2] + coordinate_dofs[10] * FE9_C1_D010_Qd8a[0][0][0][3];
    const double J_c8 = coordinate_dofs[2] * FE9_C2_D001_Qd8a[0][0][0][0] + coordinate_dofs[5] * FE9_C2_D001_Qd8a[0][0][0][1] + coordinate_dofs[8] * FE9_C2_D001_Qd8a[0][0][0][2] + coordinate_dofs[11] * FE9_C2_D001_Qd8a[0][0][0][3];
    const double J_c5 = coordinate_dofs[1] * FE9_C2_D001_Qd8a[0][0][0][0] + coordinate_dofs[4] * FE9_C2_D001_Qd8a[0][0][0][1] + coordinate_dofs[7] * FE9_C2_D001_Qd8a[0][0][0][2] + coordinate_dofs[10] * FE9_C2_D001_Qd8a[0][0][0][3];
    const double J_c7 = coordinate_dofs[2] * FE9_C1_D010_Qd8a[0][0][0][0] + coordinate_dofs[5] * FE9_C1_D010_Qd8a[0][0][0][1] + coordinate_dofs[8] * FE9_C1_D010_Qd8a[0][0][0][2] + coordinate_dofs[11] * FE9_C1_D010_Qd8a[0][0][0][3];
    const double J_c1 = coordinate_dofs[0] * FE9_C1_D010_Qd8a[0][0][0][0] + coordinate_dofs[3] * FE9_C1_D010_Qd8a[0][0][0][1] + coordinate_dofs[6] * FE9_C1_D010_Qd8a[0][0][0][2] + coordinate_dofs[9] * FE9_C1_D010_Qd8a[0][0][0][3];
    const double J_c6 = coordinate_dofs[2] * FE9_C0_D100_Qd8a[0][0][0][0] + coordinate_dofs[5] * FE9_C0_D100_Qd8a[0][0][0][1] + coordinate_dofs[8] * FE9_C0_D100_Qd8a[0][0][0][2] + coordinate_dofs[11] * FE9_C0_D100_Qd8a[0][0][0][3];
    const double J_c3 = coordinate_dofs[1] * FE9_C0_D100_Qd8a[0][0][0][0] + coordinate_dofs[4] * FE9_C0_D100_Qd8a[0][0][0][1] + coordinate_dofs[7] * FE9_C0_D100_Qd8a[0][0][0][2] + coordinate_dofs[10] * FE9_C0_D100_Qd8a[0][0][0][3];
    const double J_c2 = coordinate_dofs[0] * FE9_C2_D001_Qd8a[0][0][0][0] + coordinate_dofs[3] * FE9_C2_D001_Qd8a[0][0][0][1] + coordinate_dofs[6] * FE9_C2_D001_Qd8a[0][0][0][2] + coordinate_dofs[9] * FE9_C2_D001_Qd8a[0][0][0][3];
    ufc_scalar_t sp_d8a[15];
    sp_d8a[0] = J_c4 * J_c8;
    sp_d8a[1] = J_c5 * J_c7;
    sp_d8a[2] = sp_d8a[0] + -1 * sp_d8a[1];
    sp_d8a[3] = J_c0 * sp_d8a[2];
    sp_d8a[4] = J_c5 * J_c6;
    sp_d8a[5] = J_c3 * J_c8;
    sp_d8a[6] = sp_d8a[4] + -1 * sp_d8a[5];
    sp_d8a[7] = J_c1 * sp_d8a[6];
    sp_d8a[8] = sp_d8a[3] + sp_d8a[7];
    sp_d8a[9] = J_c3 * J_c7;
    sp_d8a[10] = J_c4 * J_c6;
    sp_d8a[11] = sp_d8a[9] + -1 * sp_d8a[10];
    sp_d8a[12] = J_c2 * sp_d8a[11];
    sp_d8a[13] = sp_d8a[8] + sp_d8a[12];
    sp_d8a[14] = fabs(sp_d8a[13]);
    for (int iq = 0; iq < 14; ++iq)
    {
        // Quadrature loop body setup for quadrature rule d8a
        // Varying computations for quadrature rule d8a
        ufc_scalar_t w0 = 0.0;
        for (int ic = 0; ic < 10; ++ic)
            w0 += w[ic] * FE11_C0_Qd8a[0][0][iq][ic];
        ufc_scalar_t sv_d8a[1];
        sv_d8a[0] = sp_d8a[14] * w0;
        const ufc_scalar_t fw0 = sv_d8a[0] * weights_d8a[iq];
        for (int i = 0; i < 10; ++i)
            A[i] += fw0 * FE11_C0_Qd8a[0][0][iq][i];
    }
}

bool enabled_coefficients_integral_2ae982a7fa3a191994f76b9ba8ae636a646a265a[1] = { false };

ufc_integral integral_2ae982a7fa3a191994f76b9ba8ae636a646a265a =
{
  .enabled_coefficients = enabled_coefficients_integral_2ae982a7fa3a191994f76b9ba8ae636a646a265a,
  .tabulate_tensor = tabulate_tensor_integral_2ae982a7fa3a191994f76b9ba8ae636a646a265a,
};

// End of code for integral integral_2ae982a7fa3a191994f76b9ba8ae636a646a265a

// Code for form form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b


ufc_dofmap* dofmaps_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b[2] = { &dofmap_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b, &dofmap_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b };
ufc_finite_element* finite_elements_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b[2] = { &element_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b, &element_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b };

// Return a list of the coefficient names.
const char** coefficient_name_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b(void)
{
return NULL;
}

// Return a list of the constant names.
const char** constant_name_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b(void)
{
return NULL;
}

int* integral_ids_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b(ufc_integral_type integral_type)
{
static int integral_ids_cell_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b[1] = { -1 };
switch (integral_type)
{
case cell:
    return integral_ids_cell_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b;
default:
    return NULL;
}
}

int num_integrals_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b(ufc_integral_type integral_type)
{
switch (integral_type)
{
case cell:
    return 1;
case interior_facet:
    return 0;
case exterior_facet:
    return 0;
default:
    return 0;
}
}

ufc_integral** integrals_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b(ufc_integral_type integral_type)
{
static ufc_integral* integrals_cell_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b[1] = { &integral_69d4cbc67251de8d7f3cd107fabff52c17b0f328 };
switch (integral_type)
{
case cell:
    return integrals_cell_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b;
default:
    return NULL;
}
}

ufc_form form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b =
{

  .signature = "72a5dd03e22cb70d76ec47bf4e981cbcf2b04d626aae2719a72c7d2da42a985d63ca5a0f081cf6aee8bd3a485b4174a8d674c176b8abddfde2092a754c293f23",
  .rank = 2,
  .num_coefficients = 0,
  .num_constants = 0,
  .original_coefficient_position = NULL,

  .coefficient_name_map = coefficient_name_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b,
  .constant_name_map = constant_name_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b,

  .finite_elements = finite_elements_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b,
  .dofmaps = dofmaps_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b,

  .integral_ids = integral_ids_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b,
  .num_integrals = num_integrals_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b,

  .integrals = integrals_form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b
};

// Alias name
ufc_form* form_problem_a = &form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b;

ufc_function_space* functionspace_form_problem_a(const char* function_name)
{
static ufc_function_space functionspace_v =
{
.finite_element = &element_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b,
.dofmap = &dofmap_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
static ufc_function_space functionspace_u =
{
.finite_element = &element_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b,
.dofmap = &dofmap_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
if (strcmp(function_name, "v") == 0)
    return &functionspace_v;
else if (strcmp(function_name, "u") == 0)
    return &functionspace_u;
return NULL;

}

// End of code for form form_10474cad3c858fa79dd48c5a94a5ea9b47988d3b

// Code for form form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01

int original_coefficient_position_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01[1] = { 0 };
ufc_dofmap* dofmaps_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01[2] = { &dofmap_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b, &dofmap_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b };
ufc_finite_element* finite_elements_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01[2] = { &element_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b, &element_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b };

// Return a list of the coefficient names.
const char** coefficient_name_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01(void)
{
static const char* names[1] = { "f" };
return names;
}

// Return a list of the constant names.
const char** constant_name_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01(void)
{
return NULL;
}

int* integral_ids_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01(ufc_integral_type integral_type)
{
static int integral_ids_cell_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01[1] = { -1 };
switch (integral_type)
{
case cell:
    return integral_ids_cell_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01;
default:
    return NULL;
}
}

int num_integrals_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01(ufc_integral_type integral_type)
{
switch (integral_type)
{
case cell:
    return 1;
case interior_facet:
    return 0;
case exterior_facet:
    return 0;
default:
    return 0;
}
}

ufc_integral** integrals_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01(ufc_integral_type integral_type)
{
static ufc_integral* integrals_cell_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01[1] = { &integral_2ae982a7fa3a191994f76b9ba8ae636a646a265a };
switch (integral_type)
{
case cell:
    return integrals_cell_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01;
default:
    return NULL;
}
}

ufc_form form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01 =
{

  .signature = "181d05b2f249e21ba84317a31c75966d958c785fda2be7d8945ffb818538c5482bc8e5194c425235fcecd651af189366011f827aca89f475a9ef93d051c73565",
  .rank = 1,
  .num_coefficients = 1,
  .num_constants = 0,
  .original_coefficient_position = original_coefficient_position_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01,

  .coefficient_name_map = coefficient_name_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01,
  .constant_name_map = constant_name_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01,

  .finite_elements = finite_elements_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01,
  .dofmaps = dofmaps_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01,

  .integral_ids = integral_ids_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01,
  .num_integrals = num_integrals_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01,

  .integrals = integrals_form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01
};

// Alias name
ufc_form* form_problem_L = &form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01;

ufc_function_space* functionspace_form_problem_L(const char* function_name)
{
static ufc_function_space functionspace_v =
{
.finite_element = &element_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b,
.dofmap = &dofmap_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
static ufc_function_space functionspace_f =
{
.finite_element = &element_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b,
.dofmap = &dofmap_79e36f7f4b7ef0738869e1c3d7601dfda8c8947b,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
if (strcmp(function_name, "v") == 0)
    return &functionspace_v;
else if (strcmp(function_name, "f") == 0)
    return &functionspace_f;
return NULL;

}

// End of code for form form_9cd2dc9c15e3a4efd752be35b2550e3a80ba7e01
