// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCX version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': 'src/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'sycl_defines': True,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['problem.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

ufc_finite_element* create_element_cfc8183014a13694f6df7ac81b3308da1bed2b3f(void);

ufc_finite_element* create_element_894eecfafddbd52dd198bd28585609e03ee06c40(void);

ufc_finite_element* create_element_546828c8d3d3a706cfb29da4de8c7144551ec821(void);

ufc_dofmap* create_dofmap_cfc8183014a13694f6df7ac81b3308da1bed2b3f(void);

ufc_dofmap* create_dofmap_894eecfafddbd52dd198bd28585609e03ee06c40(void);

ufc_dofmap* create_dofmap_546828c8d3d3a706cfb29da4de8c7144551ec821(void);

ufc_coordinate_mapping* create_coordinate_mapping_ca6860ef5739dc6bf7913612e9e04487ca134710(void);

// Helper used to create coordinate map using name given to the
// UFL file.
// This helper is called in user c++ code.
//
ufc_coordinate_mapping* create_coordinate_map_problem(void);

ufc_integral* create_integral_cell_otherwise_32dfa35028340e7d6c012f81fa6d228b6edd4b97(void);

ufc_integral* create_integral_cell_otherwise_b2e4b1e5b423dd359e732fc7707ef351a42630b5(void);

ufc_form* create_form_32dfa35028340e7d6c012f81fa6d228b6edd4b97(void);

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
ufc_form* create_form_problem_a(void);

// Helper used to create function space using its name, as given in
// the UFL file.
// Note: There are in general more function spaces associated to the form,
//       which is the reason why the helpers takes name as argument.
// This helper is called in user c++ code.
//
ufc_function_space* create_functionspace_form_problem_a(const char* fs_name);


ufc_form* create_form_b2e4b1e5b423dd359e732fc7707ef351a42630b5(void);

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
ufc_form* create_form_problem_L(void);

// Helper used to create function space using its name, as given in
// the UFL file.
// Note: There are in general more function spaces associated to the form,
//       which is the reason why the helpers takes name as argument.
// This helper is called in user c++ code.
//
ufc_function_space* create_functionspace_form_problem_L(const char* fs_name);


#ifdef __cplusplus
}
#endif
