// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCX version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': 'src/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'sycl_defines': True,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['problem.ufl'],
//   'verbosity': 30,
//   'visualise': False}


typedef double ufc_scalar_t;
#include <math.h>
#include <stdalign.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <ufc.h>

#define restrict __restrict__ 

#define space_dimension_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686 4

// Code for element element_29953d5d1a0c11d7cf01f22e6ced6740eb369686

int value_dimension_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686(int i)
{
  return 1;
}

int reference_value_dimension_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686(int i)
{
  return 1;
}

int transform_reference_basis_derivatives_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686(
    double * restrict values, int order, int num_points,
    const double * restrict reference_values,
    const double * restrict X, const double * restrict J,
    const double * restrict detJ, const double * restrict K)
{
  const int num_derivatives = pow(3, order);
// Precomputed combinations
const int combinations[1][3][1] =
    { { { 0 },
        { 1 },
        { 2 } } };
for (int l = 0; l < (num_points * 4) * num_derivatives; ++l)
    values[l] = 0.0;
for (int ip = 0; ip < num_points; ++ip)
{
    double transform[3][3];
    for (int r = 0; r < num_derivatives; ++r)
        for (int s = 0; s < num_derivatives; ++s)
            transform[r][s] = 1.0;
    for (int r = 0; r < num_derivatives; ++r)
        for (int s = 0; s < num_derivatives; ++s)
            for (int k = 0; k < order; ++k)
                transform[r][s] *= K[((3 * 3) * ip + 3 * combinations[order - 1][s][k]) + combinations[order - 1][r][k]];
    for (int d = 0; d < 4; ++d)
    {
        for (int s = 0; s < num_derivatives; ++s)
        {
            for (int i = 0; i < 1; ++i)
            {
                // Using affine transform to map values back to the physical element.
                const double mapped_value = reference_values[((4 * num_derivatives) * ip + num_derivatives * d) + s];
                // Mapping derivatives back to the physical element
                for (int r = 0; r < num_derivatives; ++r)
                    values[(((4 * num_derivatives) * ip + num_derivatives * d) + r) + i] += transform[r][s] * mapped_value;
            }
        }
    }
}
// Using affine transform to map values back to the physical element.
return 0;
}


int apply_dof_transformation_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686(
     double* restrict data, uint32_t cell_permutation, int dim)
{
  return 0;
}

int apply_dof_transformation_to_scalar_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686(
     ufc_scalar_t* restrict data, uint32_t cell_permutation, int dim)
{
  return 0;
}


ufc_finite_element* create_sub_element_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686(int i)
{
  return NULL;
}

ufc_finite_element* create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686(void)
{
  ufc_finite_element* element = (ufc_finite_element*)malloc(sizeof(*element));

  element->signature = "FiniteElement('Lagrange', tetrahedron, 1)";
  element->cell_shape = tetrahedron;
  element->topological_dimension = 3;
  element->geometric_dimension = 3;
  element->space_dimension = 4;
  element->value_rank = 0;
  element->value_dimension = value_dimension_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
  element->value_size = 1;
  element->reference_value_rank = 0;
  element->reference_value_dimension = reference_value_dimension_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
  element->reference_value_size = 1;
  element->degree = 1;
  element->family = "Lagrange";
  element->block_size = 1;

  element->needs_permutation_data = 0;
  element->interpolation_is_identity = 1;

  element->transform_reference_basis_derivatives = transform_reference_basis_derivatives_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
  element->apply_dof_transformation = apply_dof_transformation_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
  element->apply_dof_transformation_to_scalar = apply_dof_transformation_to_scalar_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
  element->num_sub_elements = 0;
  element->create_sub_element = create_sub_element_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
  element->create = create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686;

  return element;
}

// End of code for element element_29953d5d1a0c11d7cf01f22e6ced6740eb369686

#define space_dimension_element_445ef1924184cca3ac2920e3df00b14f41104dec 12

// Code for element element_445ef1924184cca3ac2920e3df00b14f41104dec

int value_dimension_element_445ef1924184cca3ac2920e3df00b14f41104dec(int i)
{
  static const int return_values[1] = { 3 };
if (i >= 1)
    return 1;
return return_values[i];
}

int reference_value_dimension_element_445ef1924184cca3ac2920e3df00b14f41104dec(int i)
{
  static const int return_values[1] = { 3 };
if (i >= 1)
    return 1;
return return_values[i];
}

int transform_reference_basis_derivatives_element_445ef1924184cca3ac2920e3df00b14f41104dec(
    double * restrict values, int order, int num_points,
    const double * restrict reference_values,
    const double * restrict X, const double * restrict J,
    const double * restrict detJ, const double * restrict K)
{
  const int num_derivatives = pow(3, order);
// Precomputed combinations
const int combinations[1][3][1] =
    { { { 0 },
        { 1 },
        { 2 } } };
for (int l = 0; l < (num_points * 4) * num_derivatives; ++l)
    values[l] = 0.0;
for (int ip = 0; ip < num_points; ++ip)
{
    double transform[3][3];
    for (int r = 0; r < num_derivatives; ++r)
        for (int s = 0; s < num_derivatives; ++s)
            transform[r][s] = 1.0;
    for (int r = 0; r < num_derivatives; ++r)
        for (int s = 0; s < num_derivatives; ++s)
            for (int k = 0; k < order; ++k)
                transform[r][s] *= K[((3 * 3) * ip + 3 * combinations[order - 1][s][k]) + combinations[order - 1][r][k]];
    for (int d = 0; d < 4; ++d)
    {
        for (int s = 0; s < num_derivatives; ++s)
        {
            for (int i = 0; i < 1; ++i)
            {
                // Using affine transform to map values back to the physical element.
                const double mapped_value = reference_values[((4 * num_derivatives) * ip + num_derivatives * d) + s];
                // Mapping derivatives back to the physical element
                for (int r = 0; r < num_derivatives; ++r)
                    values[(((4 * num_derivatives) * ip + num_derivatives * d) + r) + i] += transform[r][s] * mapped_value;
            }
        }
    }
}
// Using affine transform to map values back to the physical element.
return 0;
}


int apply_dof_transformation_element_445ef1924184cca3ac2920e3df00b14f41104dec(
     double* restrict data, uint32_t cell_permutation, int dim)
{
  return 0;
}

int apply_dof_transformation_to_scalar_element_445ef1924184cca3ac2920e3df00b14f41104dec(
     ufc_scalar_t* restrict data, uint32_t cell_permutation, int dim)
{
  return 0;
}

ufc_finite_element* create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686(void);

ufc_finite_element* create_sub_element_element_445ef1924184cca3ac2920e3df00b14f41104dec(int i)
{
  switch (i)
{
case 0:
    return create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686();
case 1:
    return create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686();
case 2:
    return create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686();
default:
    return NULL;
}
}

ufc_finite_element* create_element_445ef1924184cca3ac2920e3df00b14f41104dec(void)
{
  ufc_finite_element* element = (ufc_finite_element*)malloc(sizeof(*element));

  element->signature = "VectorElement(FiniteElement('Lagrange', tetrahedron, 1), dim=3)";
  element->cell_shape = tetrahedron;
  element->topological_dimension = 3;
  element->geometric_dimension = 3;
  element->space_dimension = 12;
  element->value_rank = 1;
  element->value_dimension = value_dimension_element_445ef1924184cca3ac2920e3df00b14f41104dec;
  element->value_size = 3;
  element->reference_value_rank = 1;
  element->reference_value_dimension = reference_value_dimension_element_445ef1924184cca3ac2920e3df00b14f41104dec;
  element->reference_value_size = 3;
  element->degree = 1;
  element->family = "Lagrange";
  element->block_size = 3;

  element->needs_permutation_data = 0;
  element->interpolation_is_identity = 1;

  element->transform_reference_basis_derivatives = transform_reference_basis_derivatives_element_445ef1924184cca3ac2920e3df00b14f41104dec;
  element->apply_dof_transformation = apply_dof_transformation_element_445ef1924184cca3ac2920e3df00b14f41104dec;
  element->apply_dof_transformation_to_scalar = apply_dof_transformation_to_scalar_element_445ef1924184cca3ac2920e3df00b14f41104dec;
  element->num_sub_elements = 3;
  element->create_sub_element = create_sub_element_element_445ef1924184cca3ac2920e3df00b14f41104dec;
  element->create = create_element_445ef1924184cca3ac2920e3df00b14f41104dec;

  return element;
}

// End of code for element element_445ef1924184cca3ac2920e3df00b14f41104dec

// Code for dofmap dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686

void tabulate_entity_dofs_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
}
}


ufc_dofmap* create_sub_dofmap_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686(int i)
{
return NULL;
}

ufc_dofmap* create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686(void)
{
  ufc_dofmap* dofmap = (ufc_dofmap*)malloc(sizeof(*dofmap));
  dofmap->signature = "FFCX dofmap for FiniteElement('Lagrange', tetrahedron, 1)";
  dofmap->block_size = 1;
  dofmap->num_global_support_dofs = 0;
  dofmap->num_element_support_dofs = 4;
  dofmap->num_entity_dofs[0] = 1;
  dofmap->num_entity_dofs[1] = 0;
  dofmap->num_entity_dofs[2] = 0;
  dofmap->num_entity_dofs[3] = 0;
  dofmap->tabulate_entity_dofs = tabulate_entity_dofs_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
  dofmap->num_sub_dofmaps = 0;
  dofmap->create_sub_dofmap = create_sub_dofmap_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
  dofmap->create = create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686;

  return dofmap;
}

// End of code for dofmap dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686

// Code for dofmap dofmap_445ef1924184cca3ac2920e3df00b14f41104dec

void tabulate_entity_dofs_dofmap_445ef1924184cca3ac2920e3df00b14f41104dec(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
}
}

ufc_dofmap* create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686(void);

ufc_dofmap* create_sub_dofmap_dofmap_445ef1924184cca3ac2920e3df00b14f41104dec(int i)
{
switch (i)
{
case 0:
    return create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686();
case 1:
    return create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686();
case 2:
    return create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686();
default:
    return NULL;
}
}

ufc_dofmap* create_dofmap_445ef1924184cca3ac2920e3df00b14f41104dec(void)
{
  ufc_dofmap* dofmap = (ufc_dofmap*)malloc(sizeof(*dofmap));
  dofmap->signature = "FFCX dofmap for VectorElement(FiniteElement('Lagrange', tetrahedron, 1), dim=3)";
  dofmap->block_size = 3;
  dofmap->num_global_support_dofs = 0;
  dofmap->num_element_support_dofs = 4;
  dofmap->num_entity_dofs[0] = 1;
  dofmap->num_entity_dofs[1] = 0;
  dofmap->num_entity_dofs[2] = 0;
  dofmap->num_entity_dofs[3] = 0;
  dofmap->tabulate_entity_dofs = tabulate_entity_dofs_dofmap_445ef1924184cca3ac2920e3df00b14f41104dec;
  dofmap->num_sub_dofmaps = 3;
  dofmap->create_sub_dofmap = create_sub_dofmap_dofmap_445ef1924184cca3ac2920e3df00b14f41104dec;
  dofmap->create = create_dofmap_445ef1924184cca3ac2920e3df00b14f41104dec;

  return dofmap;
}

// End of code for dofmap dofmap_445ef1924184cca3ac2920e3df00b14f41104dec

// Code for coordinate mapping coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd

int permute_dofs_coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd(int* dof_list, const uint32_t cell_permutation)
{
  return 0;
}

int unpermute_dofs_coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd(int* dof_list, const uint32_t cell_permutation)
{
  return 0;
}

ufc_coordinate_mapping* create_coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd(void)
{
  ufc_coordinate_mapping* cmap = (ufc_coordinate_mapping*)malloc(sizeof(*cmap));
  cmap->signature = "FFCX coordinate_mapping from VectorElement(FiniteElement('Lagrange', tetrahedron, 1), dim=3)";
  cmap->element_family = "Lagrange";
  cmap->element_degree = 1;
  cmap->create = create_coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd;
  cmap->geometric_dimension = 3;
  cmap->topological_dimension = 3;
  cmap->is_affine = 1;
  cmap->needs_permutation_data = 0;
  cmap->permute_dofs = permute_dofs_coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd;
  cmap->unpermute_dofs = unpermute_dofs_coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd;
  cmap->cell_shape = tetrahedron;
  cmap->create_scalar_dofmap = create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
  return cmap;
}

ufc_coordinate_mapping* create_coordinate_map_problem(void)
{
  return create_coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd();
}

// End of code for coordinate mapping coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd
#define tabulate_cell_a tabulate_tensor_integral_cell_otherwise_d203a4a2c772dac5857abbd4fdd2a004b73df6a4

// Code for integral integral_cell_otherwise_d203a4a2c772dac5857abbd4fdd2a004b73df6a4


void tabulate_tensor_integral_cell_otherwise_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(ufc_scalar_t* restrict A,
                                    const ufc_scalar_t* restrict w,
                                    const ufc_scalar_t* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict unused_local_index,
                                    const uint8_t* restrict quadrature_permutation,
                                    const uint32_t cell_permutation)
{
    // Quadrature rules
    static const double weights_175[5] = { -0.1333333333333333, 0.075, 0.075, 0.075, 0.075 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE8_C0_D001_Q175[1][1][1][4] = { { { { -1.0, 0.0, 0.0, 1.0 } } } };
    static const double FE8_C0_D010_Q175[1][1][1][3] = { { { { -1.0, 0.0, 1.0 } } } };
    static const double FE8_C0_D100_Q175[1][1][1][2] = { { { { -1.0, 1.0 } } } };
    static const double FE8_C0_Q175[1][1][5][4] =
        { { { { 0.2499999999999999, 0.25, 0.2499999999999999, 0.2499999999999999 },
              { 0.1666666666666667, 0.5, 0.1666666666666666, 0.1666666666666666 },
              { 0.1666666666666666, 0.1666666666666666, 0.5, 0.1666666666666665 },
              { 0.1666666666666666, 0.1666666666666666, 0.1666666666666666, 0.5 },
              { 0.5, 0.1666666666666666, 0.1666666666666666, 0.1666666666666666 } } } };
    // Quadrature loop independent computations for quadrature rule 175
    const double J_c4 = coordinate_dofs[1] * FE8_C0_D010_Q175[0][0][0][0] + coordinate_dofs[4] * FE8_C0_D010_Q175[0][0][0][1] + coordinate_dofs[7] * FE8_C0_D010_Q175[0][0][0][2];
    const double J_c8 = coordinate_dofs[2] * FE8_C0_D001_Q175[0][0][0][0] + coordinate_dofs[5] * FE8_C0_D001_Q175[0][0][0][1] + coordinate_dofs[8] * FE8_C0_D001_Q175[0][0][0][2] + coordinate_dofs[11] * FE8_C0_D001_Q175[0][0][0][3];
    const double J_c5 = coordinate_dofs[1] * FE8_C0_D001_Q175[0][0][0][0] + coordinate_dofs[4] * FE8_C0_D001_Q175[0][0][0][1] + coordinate_dofs[7] * FE8_C0_D001_Q175[0][0][0][2] + coordinate_dofs[10] * FE8_C0_D001_Q175[0][0][0][3];
    const double J_c7 = coordinate_dofs[2] * FE8_C0_D010_Q175[0][0][0][0] + coordinate_dofs[5] * FE8_C0_D010_Q175[0][0][0][1] + coordinate_dofs[8] * FE8_C0_D010_Q175[0][0][0][2];
    const double J_c0 = coordinate_dofs[0] * FE8_C0_D100_Q175[0][0][0][0] + coordinate_dofs[3] * FE8_C0_D100_Q175[0][0][0][1];
    const double J_c1 = coordinate_dofs[0] * FE8_C0_D010_Q175[0][0][0][0] + coordinate_dofs[3] * FE8_C0_D010_Q175[0][0][0][1] + coordinate_dofs[6] * FE8_C0_D010_Q175[0][0][0][2];
    const double J_c6 = coordinate_dofs[2] * FE8_C0_D100_Q175[0][0][0][0] + coordinate_dofs[5] * FE8_C0_D100_Q175[0][0][0][1];
    const double J_c3 = coordinate_dofs[1] * FE8_C0_D100_Q175[0][0][0][0] + coordinate_dofs[4] * FE8_C0_D100_Q175[0][0][0][1];
    const double J_c2 = coordinate_dofs[0] * FE8_C0_D001_Q175[0][0][0][0] + coordinate_dofs[3] * FE8_C0_D001_Q175[0][0][0][1] + coordinate_dofs[6] * FE8_C0_D001_Q175[0][0][0][2] + coordinate_dofs[9] * FE8_C0_D001_Q175[0][0][0][3];
    ufc_scalar_t sp_175[80];
    sp_175[0] = J_c4 * J_c8;
    sp_175[1] = J_c5 * J_c7;
    sp_175[2] = sp_175[0] + -1 * sp_175[1];
    sp_175[3] = J_c0 * sp_175[2];
    sp_175[4] = J_c5 * J_c6;
    sp_175[5] = J_c3 * J_c8;
    sp_175[6] = sp_175[4] + -1 * sp_175[5];
    sp_175[7] = J_c1 * sp_175[6];
    sp_175[8] = sp_175[3] + sp_175[7];
    sp_175[9] = J_c3 * J_c7;
    sp_175[10] = J_c4 * J_c6;
    sp_175[11] = sp_175[9] + -1 * sp_175[10];
    sp_175[12] = J_c2 * sp_175[11];
    sp_175[13] = sp_175[8] + sp_175[12];
    sp_175[14] = sp_175[2] / sp_175[13];
    sp_175[15] = J_c3 * (-1 * J_c8);
    sp_175[16] = sp_175[4] + sp_175[15];
    sp_175[17] = sp_175[16] / sp_175[13];
    sp_175[18] = sp_175[11] / sp_175[13];
    sp_175[19] = sp_175[14] * sp_175[14];
    sp_175[20] = sp_175[14] * sp_175[17];
    sp_175[21] = sp_175[18] * sp_175[14];
    sp_175[22] = sp_175[17] * sp_175[17];
    sp_175[23] = sp_175[18] * sp_175[17];
    sp_175[24] = sp_175[18] * sp_175[18];
    sp_175[25] = J_c2 * J_c7;
    sp_175[26] = J_c8 * (-1 * J_c1);
    sp_175[27] = sp_175[25] + sp_175[26];
    sp_175[28] = sp_175[27] / sp_175[13];
    sp_175[29] = J_c0 * J_c8;
    sp_175[30] = J_c6 * (-1 * J_c2);
    sp_175[31] = sp_175[29] + sp_175[30];
    sp_175[32] = sp_175[31] / sp_175[13];
    sp_175[33] = J_c1 * J_c6;
    sp_175[34] = J_c0 * J_c7;
    sp_175[35] = sp_175[33] + -1 * sp_175[34];
    sp_175[36] = sp_175[35] / sp_175[13];
    sp_175[37] = sp_175[28] * sp_175[28];
    sp_175[38] = sp_175[28] * sp_175[32];
    sp_175[39] = sp_175[28] * sp_175[36];
    sp_175[40] = sp_175[32] * sp_175[32];
    sp_175[41] = sp_175[32] * sp_175[36];
    sp_175[42] = sp_175[36] * sp_175[36];
    sp_175[43] = sp_175[37] + sp_175[19];
    sp_175[44] = sp_175[38] + sp_175[20];
    sp_175[45] = sp_175[39] + sp_175[21];
    sp_175[46] = sp_175[40] + sp_175[22];
    sp_175[47] = sp_175[41] + sp_175[23];
    sp_175[48] = sp_175[24] + sp_175[42];
    sp_175[49] = J_c1 * J_c5;
    sp_175[50] = J_c2 * J_c4;
    sp_175[51] = sp_175[49] + -1 * sp_175[50];
    sp_175[52] = sp_175[51] / sp_175[13];
    sp_175[53] = J_c2 * J_c3;
    sp_175[54] = J_c0 * J_c5;
    sp_175[55] = sp_175[53] + -1 * sp_175[54];
    sp_175[56] = sp_175[55] / sp_175[13];
    sp_175[57] = J_c0 * J_c4;
    sp_175[58] = J_c1 * J_c3;
    sp_175[59] = sp_175[57] + -1 * sp_175[58];
    sp_175[60] = sp_175[59] / sp_175[13];
    sp_175[61] = sp_175[52] * sp_175[52];
    sp_175[62] = sp_175[52] * sp_175[56];
    sp_175[63] = sp_175[60] * sp_175[52];
    sp_175[64] = sp_175[56] * sp_175[56];
    sp_175[65] = sp_175[60] * sp_175[56];
    sp_175[66] = sp_175[60] * sp_175[60];
    sp_175[67] = sp_175[43] + sp_175[61];
    sp_175[68] = sp_175[44] + sp_175[62];
    sp_175[69] = sp_175[45] + sp_175[63];
    sp_175[70] = sp_175[46] + sp_175[64];
    sp_175[71] = sp_175[47] + sp_175[65];
    sp_175[72] = sp_175[48] + sp_175[66];
    sp_175[73] = fabs(sp_175[13]);
    sp_175[74] = sp_175[67] * sp_175[73];
    sp_175[75] = sp_175[68] * sp_175[73];
    sp_175[76] = sp_175[69] * sp_175[73];
    sp_175[77] = sp_175[70] * sp_175[73];
    sp_175[78] = sp_175[71] * sp_175[73];
    sp_175[79] = sp_175[72] * sp_175[73];
    for (int iq = 0; iq < 5; ++iq)
    {
        const ufc_scalar_t fw0 = sp_175[74] * weights_175[iq];
        for (int i = 0; i < 2; ++i)
            for (int j = 0; j < 2; ++j)
                A[4 * i + j] += fw0 * FE8_C0_D100_Q175[0][0][0][i] * FE8_C0_D100_Q175[0][0][0][j];
        const ufc_scalar_t fw1 = sp_175[75] * weights_175[iq];
        for (int i = 0; i < 2; ++i)
            for (int j = 0; j < 3; ++j)
                A[4 * i + j] += fw1 * FE8_C0_D100_Q175[0][0][0][i] * FE8_C0_D010_Q175[0][0][0][j];
        const ufc_scalar_t fw2 = sp_175[76] * weights_175[iq];
        for (int i = 0; i < 2; ++i)
            for (int j = 0; j < 4; ++j)
                A[4 * i + j] += fw2 * FE8_C0_D100_Q175[0][0][0][i] * FE8_C0_D001_Q175[0][0][0][j];
        for (int i = 0; i < 3; ++i)
            for (int j = 0; j < 2; ++j)
                A[4 * i + j] += fw1 * FE8_C0_D010_Q175[0][0][0][i] * FE8_C0_D100_Q175[0][0][0][j];
        const ufc_scalar_t fw3 = sp_175[77] * weights_175[iq];
        for (int i = 0; i < 3; ++i)
            for (int j = 0; j < 3; ++j)
                A[4 * i + j] += fw3 * FE8_C0_D010_Q175[0][0][0][i] * FE8_C0_D010_Q175[0][0][0][j];
        const ufc_scalar_t fw4 = sp_175[78] * weights_175[iq];
        for (int i = 0; i < 3; ++i)
            for (int j = 0; j < 4; ++j)
                A[4 * i + j] += fw4 * FE8_C0_D010_Q175[0][0][0][i] * FE8_C0_D001_Q175[0][0][0][j];
        for (int i = 0; i < 4; ++i)
            for (int j = 0; j < 2; ++j)
                A[4 * i + j] += fw2 * FE8_C0_D001_Q175[0][0][0][i] * FE8_C0_D100_Q175[0][0][0][j];
        for (int i = 0; i < 4; ++i)
            for (int j = 0; j < 3; ++j)
                A[4 * i + j] += fw4 * FE8_C0_D001_Q175[0][0][0][i] * FE8_C0_D010_Q175[0][0][0][j];
        const ufc_scalar_t fw5 = sp_175[73] * weights_175[iq];
        for (int i = 0; i < 4; ++i)
            for (int j = 0; j < 4; ++j)
                A[4 * i + j] += fw5 * FE8_C0_Q175[0][0][iq][i] * FE8_C0_Q175[0][0][iq][j];
        const ufc_scalar_t fw6 = sp_175[79] * weights_175[iq];
        for (int i = 0; i < 4; ++i)
            for (int j = 0; j < 4; ++j)
                A[4 * i + j] += fw6 * FE8_C0_D001_Q175[0][0][0][i] * FE8_C0_D001_Q175[0][0][0][j];
    }
}


ufc_integral* create_integral_cell_otherwise_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(void)
{
  static const bool enabled[1] = {false};  /* No coefficients, but C does not permit zero-sized arrays */
  ufc_integral* integral = (ufc_integral*)malloc(sizeof(*integral));
  integral->enabled_coefficients = enabled;
  integral->tabulate_tensor = tabulate_tensor_integral_cell_otherwise_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;
  integral->needs_permutation_data = 0;
  return integral;
}

// End of code for integral integral_cell_otherwise_d203a4a2c772dac5857abbd4fdd2a004b73df6a4
#define tabulate_cell_L tabulate_tensor_integral_cell_otherwise_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb

// Code for integral integral_cell_otherwise_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb


void tabulate_tensor_integral_cell_otherwise_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(ufc_scalar_t* restrict A,
                                    const ufc_scalar_t* restrict w,
                                    const ufc_scalar_t* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict unused_local_index,
                                    const uint8_t* restrict quadrature_permutation,
                                    const uint32_t cell_permutation)
{
    // Quadrature rules
    static const double weights_175[5] = { -0.1333333333333333, 0.075, 0.075, 0.075, 0.075 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE8_C0_Q175[1][1][5][4] =
        { { { { 0.2499999999999999, 0.25, 0.2499999999999999, 0.2499999999999999 },
              { 0.1666666666666667, 0.5, 0.1666666666666666, 0.1666666666666666 },
              { 0.1666666666666666, 0.1666666666666666, 0.5, 0.1666666666666665 },
              { 0.1666666666666666, 0.1666666666666666, 0.1666666666666666, 0.5 },
              { 0.5, 0.1666666666666666, 0.1666666666666666, 0.1666666666666666 } } } };
    static const double FE9_C0_D001_Q175[1][1][1][4] = { { { { -1.0, 0.0, 0.0, 1.0 } } } };
    static const double FE9_C0_D010_Q175[1][1][1][3] = { { { { -1.0, 0.0, 1.0 } } } };
    static const double FE9_C0_D100_Q175[1][1][1][2] = { { { { -1.0, 1.0 } } } };
    // Quadrature loop independent computations for quadrature rule 175
    const double J_c0 = coordinate_dofs[0] * FE9_C0_D100_Q175[0][0][0][0] + coordinate_dofs[3] * FE9_C0_D100_Q175[0][0][0][1];
    const double J_c4 = coordinate_dofs[1] * FE9_C0_D010_Q175[0][0][0][0] + coordinate_dofs[4] * FE9_C0_D010_Q175[0][0][0][1] + coordinate_dofs[7] * FE9_C0_D010_Q175[0][0][0][2];
    const double J_c8 = coordinate_dofs[2] * FE9_C0_D001_Q175[0][0][0][0] + coordinate_dofs[5] * FE9_C0_D001_Q175[0][0][0][1] + coordinate_dofs[8] * FE9_C0_D001_Q175[0][0][0][2] + coordinate_dofs[11] * FE9_C0_D001_Q175[0][0][0][3];
    const double J_c5 = coordinate_dofs[1] * FE9_C0_D001_Q175[0][0][0][0] + coordinate_dofs[4] * FE9_C0_D001_Q175[0][0][0][1] + coordinate_dofs[7] * FE9_C0_D001_Q175[0][0][0][2] + coordinate_dofs[10] * FE9_C0_D001_Q175[0][0][0][3];
    const double J_c7 = coordinate_dofs[2] * FE9_C0_D010_Q175[0][0][0][0] + coordinate_dofs[5] * FE9_C0_D010_Q175[0][0][0][1] + coordinate_dofs[8] * FE9_C0_D010_Q175[0][0][0][2];
    const double J_c1 = coordinate_dofs[0] * FE9_C0_D010_Q175[0][0][0][0] + coordinate_dofs[3] * FE9_C0_D010_Q175[0][0][0][1] + coordinate_dofs[6] * FE9_C0_D010_Q175[0][0][0][2];
    const double J_c6 = coordinate_dofs[2] * FE9_C0_D100_Q175[0][0][0][0] + coordinate_dofs[5] * FE9_C0_D100_Q175[0][0][0][1];
    const double J_c3 = coordinate_dofs[1] * FE9_C0_D100_Q175[0][0][0][0] + coordinate_dofs[4] * FE9_C0_D100_Q175[0][0][0][1];
    const double J_c2 = coordinate_dofs[0] * FE9_C0_D001_Q175[0][0][0][0] + coordinate_dofs[3] * FE9_C0_D001_Q175[0][0][0][1] + coordinate_dofs[6] * FE9_C0_D001_Q175[0][0][0][2] + coordinate_dofs[9] * FE9_C0_D001_Q175[0][0][0][3];
    ufc_scalar_t sp_175[15];
    sp_175[0] = J_c4 * J_c8;
    sp_175[1] = J_c5 * J_c7;
    sp_175[2] = sp_175[0] + -1 * sp_175[1];
    sp_175[3] = J_c0 * sp_175[2];
    sp_175[4] = J_c5 * J_c6;
    sp_175[5] = J_c3 * J_c8;
    sp_175[6] = sp_175[4] + -1 * sp_175[5];
    sp_175[7] = J_c1 * sp_175[6];
    sp_175[8] = sp_175[3] + sp_175[7];
    sp_175[9] = J_c3 * J_c7;
    sp_175[10] = J_c4 * J_c6;
    sp_175[11] = sp_175[9] + -1 * sp_175[10];
    sp_175[12] = J_c2 * sp_175[11];
    sp_175[13] = sp_175[8] + sp_175[12];
    sp_175[14] = fabs(sp_175[13]);
    for (int iq = 0; iq < 5; ++iq)
    {
        // Quadrature loop body setup for quadrature rule 175
        // Varying computations for quadrature rule 175
        ufc_scalar_t w0 = 0.0;
        for (int ic = 0; ic < 4; ++ic)
            w0 += w[ic] * FE8_C0_Q175[0][0][iq][ic];
        ufc_scalar_t sv_175[1];
        sv_175[0] = sp_175[14] * w0;
        const ufc_scalar_t fw0 = sv_175[0] * weights_175[iq];
        for (int i = 0; i < 4; ++i)
            A[i] += fw0 * FE8_C0_Q175[0][0][iq][i];
    }
}


ufc_integral* create_integral_cell_otherwise_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(void)
{
  static const bool enabled[1] = { true };
  ufc_integral* integral = (ufc_integral*)malloc(sizeof(*integral));
  integral->enabled_coefficients = enabled;
  integral->tabulate_tensor = tabulate_tensor_integral_cell_otherwise_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;
  integral->needs_permutation_data = 0;
  return integral;
}

// End of code for integral integral_cell_otherwise_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb
#define a_num_dofs space_dimension_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686

// Code for form form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4

int original_coefficient_position_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(int i)
{
// Invalid original coefficient index.
return -1;
}

// Return a list of the coefficient names.
const char** coefficient_name_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(void)
{
return NULL;
}

// Return a list of the constant names.
const char** constant_name_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(void)
{
return NULL;
}

ufc_coordinate_mapping* create_coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd(void);

ufc_coordinate_mapping* create_coordinate_mapping_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(void)
{
return create_coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd();
}

ufc_finite_element* create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686(void);

ufc_finite_element* create_finite_element_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(int i)
{
switch (i)
{
case 0:
    return create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686();
case 1:
    return create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686();
default:
    return NULL;
}
}

ufc_dofmap* create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686(void);

ufc_dofmap* create_dofmap_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(int i)
{
switch (i)
{
case 0:
    return create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686();
case 1:
    return create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686();
default:
    return NULL;
}
}

ufc_integral* create_cell_integral_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(int subdomain_id)
{
  switch (subdomain_id)
{
case -1:
    return create_integral_cell_otherwise_d203a4a2c772dac5857abbd4fdd2a004b73df6a4();
default:
    return NULL;
}
}

void get_cell_integral_ids_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(int *ids)
{
  ids[0] = -1;
return;
}

ufc_integral* create_exterior_facet_integral_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(int subdomain_id)
{
  return NULL;
}

void get_exterior_facet_integral_ids_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(int *ids)
{
  return;
}

ufc_integral* create_interior_facet_integral_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(int subdomain_id)
{
return NULL;
}

void get_interior_facet_integral_ids_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(int *ids)
{
  return;
}

ufc_integral* create_vertex_integral_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(int subdomain_id)
{
return NULL;
}

void get_vertex_integral_ids_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(int *ids)
{
  return;
}

ufc_custom_integral* create_custom_integral_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(int subdomain_id)
{
return NULL;
}

void get_custom_integral_ids_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(int *ids)
{
  return;
}

ufc_form* create_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4(void)
{
  ufc_form* form = (ufc_form*)malloc(sizeof(*form));

  form->signature = "f926a764b806bd19d493250d1cb24c767be417cfaf5266094420bc91e30b1ab8aaa449aa65e1cc2bb5506f901f4c5c83020b9c0f1dbfb8e658b99153f701c283";
  form->rank = 2;
  form->num_coefficients = 0;
  form->num_constants = 0;
  form->original_coefficient_position = original_coefficient_position_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;

  form->coefficient_name_map = coefficient_name_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;
  form->constant_name_map = constant_name_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;

  form->create_coordinate_mapping = create_coordinate_mapping_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;
  form->create_finite_element = create_finite_element_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;
  form->create_dofmap = create_dofmap_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;

  form->get_cell_integral_ids = get_cell_integral_ids_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;
  form->get_exterior_facet_integral_ids = get_exterior_facet_integral_ids_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;
  form->get_interior_facet_integral_ids = get_interior_facet_integral_ids_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;
  form->get_vertex_integral_ids = get_vertex_integral_ids_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;
  form->get_custom_integral_ids = get_custom_integral_ids_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;

  form->num_cell_integrals = 1;
  form->num_exterior_facet_integrals = 0;
  form->num_interior_facet_integrals = 0;
  form->num_vertex_integrals = 0;
  form->num_custom_integrals = 0;

  form->create_cell_integral = create_cell_integral_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;
  form->create_exterior_facet_integral = create_exterior_facet_integral_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;
  form->create_interior_facet_integral = create_interior_facet_integral_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;
  form->create_vertex_integral = create_vertex_integral_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;
  form->create_custom_integral = create_custom_integral_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4;

  return form;
}

ufc_form* create_form_problem_a(void)
{
  return create_form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4();
}

ufc_function_space* create_functionspace_form_problem_a(const char* function_name)
{
  if (strcmp(function_name, "v") == 0)
{
    ufc_function_space* space = (ufc_function_space*)malloc(sizeof(*space));
    space->create_element = create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
    space->create_dofmap = create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
    space->create_coordinate_mapping = create_coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd;
    return space;
}
else if (strcmp(function_name, "u") == 0)
{
    ufc_function_space* space = (ufc_function_space*)malloc(sizeof(*space));
    space->create_element = create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
    space->create_dofmap = create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
    space->create_coordinate_mapping = create_coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd;
    return space;
}
return NULL;

}

// End of code for form form_d203a4a2c772dac5857abbd4fdd2a004b73df6a4
#define L_num_dofs space_dimension_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686

// Code for form form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb

int original_coefficient_position_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(int i)
{
if (i >= 1)
{
    // Invalid original coefficient index.
    return -1;
}
static const int position[1] = { 0 };
return position[i];
}

// Return a list of the coefficient names.
const char** coefficient_name_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(void)
{
static const char* names[1] = { "f" };
return names;
}

// Return a list of the constant names.
const char** constant_name_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(void)
{
return NULL;
}

ufc_coordinate_mapping* create_coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd(void);

ufc_coordinate_mapping* create_coordinate_mapping_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(void)
{
return create_coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd();
}

ufc_finite_element* create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686(void);

ufc_finite_element* create_finite_element_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(int i)
{
switch (i)
{
case 0:
    return create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686();
case 1:
    return create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686();
default:
    return NULL;
}
}

ufc_dofmap* create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686(void);

ufc_dofmap* create_dofmap_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(int i)
{
switch (i)
{
case 0:
    return create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686();
case 1:
    return create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686();
default:
    return NULL;
}
}

ufc_integral* create_cell_integral_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(int subdomain_id)
{
  switch (subdomain_id)
{
case -1:
    return create_integral_cell_otherwise_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb();
default:
    return NULL;
}
}

void get_cell_integral_ids_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(int *ids)
{
  ids[0] = -1;
return;
}

ufc_integral* create_exterior_facet_integral_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(int subdomain_id)
{
  return NULL;
}

void get_exterior_facet_integral_ids_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(int *ids)
{
  return;
}

ufc_integral* create_interior_facet_integral_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(int subdomain_id)
{
return NULL;
}

void get_interior_facet_integral_ids_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(int *ids)
{
  return;
}

ufc_integral* create_vertex_integral_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(int subdomain_id)
{
return NULL;
}

void get_vertex_integral_ids_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(int *ids)
{
  return;
}

ufc_custom_integral* create_custom_integral_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(int subdomain_id)
{
return NULL;
}

void get_custom_integral_ids_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(int *ids)
{
  return;
}

ufc_form* create_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb(void)
{
  ufc_form* form = (ufc_form*)malloc(sizeof(*form));

  form->signature = "44106fd01405fbd79a786ee9e6b6ca66032a217066d9f7e89d62509a023009da7f35d5d45d512d692f78fb6870e876cb1de1a826ceb3fcbf1de7c735e46b5b08";
  form->rank = 1;
  form->num_coefficients = 1;
  form->num_constants = 0;
  form->original_coefficient_position = original_coefficient_position_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;

  form->coefficient_name_map = coefficient_name_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;
  form->constant_name_map = constant_name_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;

  form->create_coordinate_mapping = create_coordinate_mapping_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;
  form->create_finite_element = create_finite_element_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;
  form->create_dofmap = create_dofmap_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;

  form->get_cell_integral_ids = get_cell_integral_ids_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;
  form->get_exterior_facet_integral_ids = get_exterior_facet_integral_ids_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;
  form->get_interior_facet_integral_ids = get_interior_facet_integral_ids_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;
  form->get_vertex_integral_ids = get_vertex_integral_ids_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;
  form->get_custom_integral_ids = get_custom_integral_ids_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;

  form->num_cell_integrals = 1;
  form->num_exterior_facet_integrals = 0;
  form->num_interior_facet_integrals = 0;
  form->num_vertex_integrals = 0;
  form->num_custom_integrals = 0;

  form->create_cell_integral = create_cell_integral_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;
  form->create_exterior_facet_integral = create_exterior_facet_integral_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;
  form->create_interior_facet_integral = create_interior_facet_integral_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;
  form->create_vertex_integral = create_vertex_integral_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;
  form->create_custom_integral = create_custom_integral_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb;

  return form;
}

ufc_form* create_form_problem_L(void)
{
  return create_form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb();
}

ufc_function_space* create_functionspace_form_problem_L(const char* function_name)
{
  if (strcmp(function_name, "v") == 0)
{
    ufc_function_space* space = (ufc_function_space*)malloc(sizeof(*space));
    space->create_element = create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
    space->create_dofmap = create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
    space->create_coordinate_mapping = create_coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd;
    return space;
}
else if (strcmp(function_name, "f") == 0)
{
    ufc_function_space* space = (ufc_function_space*)malloc(sizeof(*space));
    space->create_element = create_element_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
    space->create_dofmap = create_dofmap_29953d5d1a0c11d7cf01f22e6ced6740eb369686;
    space->create_coordinate_mapping = create_coordinate_mapping_1f89a57b7e70aa7fa9dd34a9d04c20d765fb89fd;
    return space;
}
return NULL;

}

// End of code for form form_17724f7a3e41d0a56ce5c3d3fd327eac39ee3fcb
