// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.1.0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': 'src/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['problem.ufl'],
//   'verbosity': 30,
//   'visualise': False}


typedef double ufc_scalar_t;
#include <math.h>
#include <stdalign.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <ufc.h>

// Code for element element_8e2ddea2c2f726e9e0db250bec514d348ab6d807





ufc_finite_element element_8e2ddea2c2f726e9e0db250bec514d348ab6d807 =
{
  .signature = "FiniteElement('Lagrange', tetrahedron, 1)",
  .cell_shape = tetrahedron,
  .topological_dimension = 3,
  .geometric_dimension = 3,
  .space_dimension = 4,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .family = "Lagrange",
  .block_size = 1,

  .needs_transformation_data = 0,

  .num_sub_elements = 0,
  .sub_elements = NULL
};

// End of code for element element_8e2ddea2c2f726e9e0db250bec514d348ab6d807

// Code for element element_27f95bf0dd057a9618c355be3a85ab8fe29c1039

int value_shape_element_27f95bf0dd057a9618c355be3a85ab8fe29c1039[1] = { 3 };
int reference_value_shape_element_27f95bf0dd057a9618c355be3a85ab8fe29c1039[1] = { 3 };
ufc_finite_element* sub_elements_element_27f95bf0dd057a9618c355be3a85ab8fe29c1039[3] = { &element_8e2ddea2c2f726e9e0db250bec514d348ab6d807, &element_8e2ddea2c2f726e9e0db250bec514d348ab6d807, &element_8e2ddea2c2f726e9e0db250bec514d348ab6d807 };

ufc_finite_element element_27f95bf0dd057a9618c355be3a85ab8fe29c1039 =
{
  .signature = "VectorElement(FiniteElement('Lagrange', tetrahedron, 1), dim=3)",
  .cell_shape = tetrahedron,
  .topological_dimension = 3,
  .geometric_dimension = 3,
  .space_dimension = 12,
  .value_rank = 1,
  .value_shape = value_shape_element_27f95bf0dd057a9618c355be3a85ab8fe29c1039,
  .value_size = 3,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_27f95bf0dd057a9618c355be3a85ab8fe29c1039,
  .reference_value_size = 3,
  .degree = 1,
  .family = "Lagrange",
  .block_size = 3,

  .needs_transformation_data = 0,

  .num_sub_elements = 3,
  .sub_elements = sub_elements_element_27f95bf0dd057a9618c355be3a85ab8fe29c1039
};

// End of code for element element_27f95bf0dd057a9618c355be3a85ab8fe29c1039

// Code for dofmap dofmap_8e2ddea2c2f726e9e0db250bec514d348ab6d807



void tabulate_entity_dofs_dofmap_8e2ddea2c2f726e9e0db250bec514d348ab6d807(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
}
}

ufc_dofmap dofmap_8e2ddea2c2f726e9e0db250bec514d348ab6d807 =
{
  .signature = "FFCx dofmap for FiniteElement('Lagrange', tetrahedron, 1)",
  .block_size = 1,
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 4,
  .num_entity_dofs[0] = 1,
  .num_entity_dofs[1] = 0,
  .num_entity_dofs[2] = 0,
  .num_entity_dofs[3] = 0,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_8e2ddea2c2f726e9e0db250bec514d348ab6d807,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_8e2ddea2c2f726e9e0db250bec514d348ab6d807

// Code for dofmap dofmap_27f95bf0dd057a9618c355be3a85ab8fe29c1039

ufc_dofmap* sub_dofmaps_dofmap_27f95bf0dd057a9618c355be3a85ab8fe29c1039[3] = { &dofmap_8e2ddea2c2f726e9e0db250bec514d348ab6d807, &dofmap_8e2ddea2c2f726e9e0db250bec514d348ab6d807, &dofmap_8e2ddea2c2f726e9e0db250bec514d348ab6d807 };

void tabulate_entity_dofs_dofmap_27f95bf0dd057a9618c355be3a85ab8fe29c1039(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
}
}

ufc_dofmap dofmap_27f95bf0dd057a9618c355be3a85ab8fe29c1039 =
{
  .signature = "FFCx dofmap for VectorElement(FiniteElement('Lagrange', tetrahedron, 1), dim=3)",
  .block_size = 3,
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 4,
  .num_entity_dofs[0] = 1,
  .num_entity_dofs[1] = 0,
  .num_entity_dofs[2] = 0,
  .num_entity_dofs[3] = 0,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_27f95bf0dd057a9618c355be3a85ab8fe29c1039,
  .num_sub_dofmaps = 3,
  .sub_dofmaps = sub_dofmaps_dofmap_27f95bf0dd057a9618c355be3a85ab8fe29c1039
};

// End of code for dofmap dofmap_27f95bf0dd057a9618c355be3a85ab8fe29c1039

// Code for integral integral_dcc557d3a90e447473a071b6b240c36c2de6fcaf

void tabulate_tensor_integral_dcc557d3a90e447473a071b6b240c36c2de6fcaf(ufc_scalar_t* restrict A,
                                    const ufc_scalar_t* restrict w,
                                    const ufc_scalar_t* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation,
                                    const uint32_t cell_permutation)
{
    // Quadrature rules
    static const double weights_fad[4] = { 0.04166666666666666, 0.04166666666666666, 0.04166666666666666, 0.04166666666666666 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE8_C0_D100_Qfad[1][1][1][4] = { { { { -1.0, 1.0, 0.0, 0.0 } } } };
    static const double FE8_C0_Qfad[1][1][4][4] =
        { { { { 0.1381966011250091, 0.5854101966249688, 0.138196601125011, 0.1381966011250109 },
              { 0.1381966011250091, 0.138196601125011, 0.5854101966249688, 0.1381966011250109 },
              { 0.1381966011250092, 0.1381966011250111, 0.1381966011250111, 0.585410196624969 },
              { 0.585410196624967, 0.1381966011250109, 0.138196601125011, 0.1381966011250109 } } } };
    static const double FE9_C1_D010_Qfad[1][1][1][4] = { { { { -1.0, 0.0, 1.0, 0.0 } } } };
    static const double FE9_C2_D001_Qfad[1][1][1][4] = { { { { -1.0, 0.0, 0.0, 1.0 } } } };
    // Quadrature loop independent computations for quadrature rule fad
    const double J_c4 = coordinate_dofs[1] * FE9_C1_D010_Qfad[0][0][0][0] + coordinate_dofs[4] * FE9_C1_D010_Qfad[0][0][0][1] + coordinate_dofs[7] * FE9_C1_D010_Qfad[0][0][0][2] + coordinate_dofs[10] * FE9_C1_D010_Qfad[0][0][0][3];
    const double J_c8 = coordinate_dofs[2] * FE9_C2_D001_Qfad[0][0][0][0] + coordinate_dofs[5] * FE9_C2_D001_Qfad[0][0][0][1] + coordinate_dofs[8] * FE9_C2_D001_Qfad[0][0][0][2] + coordinate_dofs[11] * FE9_C2_D001_Qfad[0][0][0][3];
    const double J_c5 = coordinate_dofs[1] * FE9_C2_D001_Qfad[0][0][0][0] + coordinate_dofs[4] * FE9_C2_D001_Qfad[0][0][0][1] + coordinate_dofs[7] * FE9_C2_D001_Qfad[0][0][0][2] + coordinate_dofs[10] * FE9_C2_D001_Qfad[0][0][0][3];
    const double J_c7 = coordinate_dofs[2] * FE9_C1_D010_Qfad[0][0][0][0] + coordinate_dofs[5] * FE9_C1_D010_Qfad[0][0][0][1] + coordinate_dofs[8] * FE9_C1_D010_Qfad[0][0][0][2] + coordinate_dofs[11] * FE9_C1_D010_Qfad[0][0][0][3];
    const double J_c0 = coordinate_dofs[0] * FE8_C0_D100_Qfad[0][0][0][0] + coordinate_dofs[3] * FE8_C0_D100_Qfad[0][0][0][1] + coordinate_dofs[6] * FE8_C0_D100_Qfad[0][0][0][2] + coordinate_dofs[9] * FE8_C0_D100_Qfad[0][0][0][3];
    const double J_c1 = coordinate_dofs[0] * FE9_C1_D010_Qfad[0][0][0][0] + coordinate_dofs[3] * FE9_C1_D010_Qfad[0][0][0][1] + coordinate_dofs[6] * FE9_C1_D010_Qfad[0][0][0][2] + coordinate_dofs[9] * FE9_C1_D010_Qfad[0][0][0][3];
    const double J_c6 = coordinate_dofs[2] * FE8_C0_D100_Qfad[0][0][0][0] + coordinate_dofs[5] * FE8_C0_D100_Qfad[0][0][0][1] + coordinate_dofs[8] * FE8_C0_D100_Qfad[0][0][0][2] + coordinate_dofs[11] * FE8_C0_D100_Qfad[0][0][0][3];
    const double J_c3 = coordinate_dofs[1] * FE8_C0_D100_Qfad[0][0][0][0] + coordinate_dofs[4] * FE8_C0_D100_Qfad[0][0][0][1] + coordinate_dofs[7] * FE8_C0_D100_Qfad[0][0][0][2] + coordinate_dofs[10] * FE8_C0_D100_Qfad[0][0][0][3];
    const double J_c2 = coordinate_dofs[0] * FE9_C2_D001_Qfad[0][0][0][0] + coordinate_dofs[3] * FE9_C2_D001_Qfad[0][0][0][1] + coordinate_dofs[6] * FE9_C2_D001_Qfad[0][0][0][2] + coordinate_dofs[9] * FE9_C2_D001_Qfad[0][0][0][3];
    ufc_scalar_t sp_fad[80];
    sp_fad[0] = J_c4 * J_c8;
    sp_fad[1] = J_c5 * J_c7;
    sp_fad[2] = sp_fad[0] + -1 * sp_fad[1];
    sp_fad[3] = J_c0 * sp_fad[2];
    sp_fad[4] = J_c5 * J_c6;
    sp_fad[5] = J_c3 * J_c8;
    sp_fad[6] = sp_fad[4] + -1 * sp_fad[5];
    sp_fad[7] = J_c1 * sp_fad[6];
    sp_fad[8] = sp_fad[3] + sp_fad[7];
    sp_fad[9] = J_c3 * J_c7;
    sp_fad[10] = J_c4 * J_c6;
    sp_fad[11] = sp_fad[9] + -1 * sp_fad[10];
    sp_fad[12] = J_c2 * sp_fad[11];
    sp_fad[13] = sp_fad[8] + sp_fad[12];
    sp_fad[14] = sp_fad[2] / sp_fad[13];
    sp_fad[15] = J_c3 * (-1 * J_c8);
    sp_fad[16] = sp_fad[4] + sp_fad[15];
    sp_fad[17] = sp_fad[16] / sp_fad[13];
    sp_fad[18] = sp_fad[11] / sp_fad[13];
    sp_fad[19] = sp_fad[14] * sp_fad[14];
    sp_fad[20] = sp_fad[14] * sp_fad[17];
    sp_fad[21] = sp_fad[18] * sp_fad[14];
    sp_fad[22] = sp_fad[17] * sp_fad[17];
    sp_fad[23] = sp_fad[18] * sp_fad[17];
    sp_fad[24] = sp_fad[18] * sp_fad[18];
    sp_fad[25] = J_c2 * J_c7;
    sp_fad[26] = J_c8 * (-1 * J_c1);
    sp_fad[27] = sp_fad[25] + sp_fad[26];
    sp_fad[28] = sp_fad[27] / sp_fad[13];
    sp_fad[29] = J_c0 * J_c8;
    sp_fad[30] = J_c6 * (-1 * J_c2);
    sp_fad[31] = sp_fad[29] + sp_fad[30];
    sp_fad[32] = sp_fad[31] / sp_fad[13];
    sp_fad[33] = J_c1 * J_c6;
    sp_fad[34] = J_c0 * J_c7;
    sp_fad[35] = sp_fad[33] + -1 * sp_fad[34];
    sp_fad[36] = sp_fad[35] / sp_fad[13];
    sp_fad[37] = sp_fad[28] * sp_fad[28];
    sp_fad[38] = sp_fad[28] * sp_fad[32];
    sp_fad[39] = sp_fad[28] * sp_fad[36];
    sp_fad[40] = sp_fad[32] * sp_fad[32];
    sp_fad[41] = sp_fad[32] * sp_fad[36];
    sp_fad[42] = sp_fad[36] * sp_fad[36];
    sp_fad[43] = sp_fad[37] + sp_fad[19];
    sp_fad[44] = sp_fad[38] + sp_fad[20];
    sp_fad[45] = sp_fad[39] + sp_fad[21];
    sp_fad[46] = sp_fad[40] + sp_fad[22];
    sp_fad[47] = sp_fad[41] + sp_fad[23];
    sp_fad[48] = sp_fad[24] + sp_fad[42];
    sp_fad[49] = J_c1 * J_c5;
    sp_fad[50] = J_c2 * J_c4;
    sp_fad[51] = sp_fad[49] + -1 * sp_fad[50];
    sp_fad[52] = sp_fad[51] / sp_fad[13];
    sp_fad[53] = J_c2 * J_c3;
    sp_fad[54] = J_c0 * J_c5;
    sp_fad[55] = sp_fad[53] + -1 * sp_fad[54];
    sp_fad[56] = sp_fad[55] / sp_fad[13];
    sp_fad[57] = J_c0 * J_c4;
    sp_fad[58] = J_c1 * J_c3;
    sp_fad[59] = sp_fad[57] + -1 * sp_fad[58];
    sp_fad[60] = sp_fad[59] / sp_fad[13];
    sp_fad[61] = sp_fad[52] * sp_fad[52];
    sp_fad[62] = sp_fad[52] * sp_fad[56];
    sp_fad[63] = sp_fad[60] * sp_fad[52];
    sp_fad[64] = sp_fad[56] * sp_fad[56];
    sp_fad[65] = sp_fad[60] * sp_fad[56];
    sp_fad[66] = sp_fad[60] * sp_fad[60];
    sp_fad[67] = sp_fad[43] + sp_fad[61];
    sp_fad[68] = sp_fad[44] + sp_fad[62];
    sp_fad[69] = sp_fad[45] + sp_fad[63];
    sp_fad[70] = sp_fad[46] + sp_fad[64];
    sp_fad[71] = sp_fad[47] + sp_fad[65];
    sp_fad[72] = sp_fad[48] + sp_fad[66];
    sp_fad[73] = fabs(sp_fad[13]);
    sp_fad[74] = sp_fad[67] * sp_fad[73];
    sp_fad[75] = sp_fad[68] * sp_fad[73];
    sp_fad[76] = sp_fad[69] * sp_fad[73];
    sp_fad[77] = sp_fad[70] * sp_fad[73];
    sp_fad[78] = sp_fad[71] * sp_fad[73];
    sp_fad[79] = sp_fad[72] * sp_fad[73];
    for (int iq = 0; iq < 4; ++iq)
    {
        const ufc_scalar_t fw0 = sp_fad[73] * weights_fad[iq];
        const ufc_scalar_t fw1 = sp_fad[74] * weights_fad[iq];
        const ufc_scalar_t fw2 = sp_fad[75] * weights_fad[iq];
        const ufc_scalar_t fw3 = sp_fad[76] * weights_fad[iq];
        const ufc_scalar_t fw4 = sp_fad[77] * weights_fad[iq];
        const ufc_scalar_t fw5 = sp_fad[78] * weights_fad[iq];
        const ufc_scalar_t fw6 = sp_fad[79] * weights_fad[iq];
        ufc_scalar_t t0[4];
        ufc_scalar_t t1[4];
        ufc_scalar_t t2[4];
        ufc_scalar_t t3[4];
        for (int i = 0; i < 4; ++i)
        {
            t0[i] = fw0 * FE8_C0_Qfad[0][0][iq][i];
            t1[i] = fw1 * FE8_C0_D100_Qfad[0][0][0][i] + fw2 * FE9_C1_D010_Qfad[0][0][0][i] + fw3 * FE9_C2_D001_Qfad[0][0][0][i];
            t2[i] = fw2 * FE8_C0_D100_Qfad[0][0][0][i] + fw4 * FE9_C1_D010_Qfad[0][0][0][i] + fw5 * FE9_C2_D001_Qfad[0][0][0][i];
            t3[i] = fw3 * FE8_C0_D100_Qfad[0][0][0][i] + fw5 * FE9_C1_D010_Qfad[0][0][0][i] + fw6 * FE9_C2_D001_Qfad[0][0][0][i];
        }
        for (int i = 0; i < 4; ++i)
        {
            for (int j = 0; j < 4; ++j)
            {
                ufc_scalar_t acc0 = 0;
                acc0 += FE8_C0_Qfad[0][0][iq][j] * t0[i];
                acc0 += FE8_C0_D100_Qfad[0][0][0][j] * t1[i];
                acc0 += FE9_C1_D010_Qfad[0][0][0][j] * t2[i];
                acc0 += FE9_C2_D001_Qfad[0][0][0][j] * t3[i];
                A[4 * i + j] += acc0;
            }
        }
    }
}



ufc_integral integral_dcc557d3a90e447473a071b6b240c36c2de6fcaf =
{
  .enabled_coefficients = NULL,
  .tabulate_tensor = tabulate_tensor_integral_dcc557d3a90e447473a071b6b240c36c2de6fcaf,
  .needs_transformation_data = 0
};

// End of code for integral integral_dcc557d3a90e447473a071b6b240c36c2de6fcaf

// Code for integral integral_e662eb318e752baadbe6a15e0a8dd3a9e542583e

void tabulate_tensor_integral_e662eb318e752baadbe6a15e0a8dd3a9e542583e(ufc_scalar_t* restrict A,
                                    const ufc_scalar_t* restrict w,
                                    const ufc_scalar_t* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation,
                                    const uint32_t cell_permutation)
{
    // Quadrature rules
    static const double weights_fad[4] = { 0.04166666666666666, 0.04166666666666666, 0.04166666666666666, 0.04166666666666666 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE8_C0_Qfad[1][1][4][4] =
        { { { { 0.1381966011250091, 0.5854101966249688, 0.138196601125011, 0.1381966011250109 },
              { 0.1381966011250091, 0.138196601125011, 0.5854101966249688, 0.1381966011250109 },
              { 0.1381966011250092, 0.1381966011250111, 0.1381966011250111, 0.585410196624969 },
              { 0.585410196624967, 0.1381966011250109, 0.138196601125011, 0.1381966011250109 } } } };
    static const double FE9_C0_D100_Qfad[1][1][1][4] = { { { { -1.0, 1.0, 0.0, 0.0 } } } };
    static const double FE9_C1_D010_Qfad[1][1][1][4] = { { { { -1.0, 0.0, 1.0, 0.0 } } } };
    static const double FE9_C2_D001_Qfad[1][1][1][4] = { { { { -1.0, 0.0, 0.0, 1.0 } } } };
    // Quadrature loop independent computations for quadrature rule fad
    const double J_c0 = coordinate_dofs[0] * FE9_C0_D100_Qfad[0][0][0][0] + coordinate_dofs[3] * FE9_C0_D100_Qfad[0][0][0][1] + coordinate_dofs[6] * FE9_C0_D100_Qfad[0][0][0][2] + coordinate_dofs[9] * FE9_C0_D100_Qfad[0][0][0][3];
    const double J_c4 = coordinate_dofs[1] * FE9_C1_D010_Qfad[0][0][0][0] + coordinate_dofs[4] * FE9_C1_D010_Qfad[0][0][0][1] + coordinate_dofs[7] * FE9_C1_D010_Qfad[0][0][0][2] + coordinate_dofs[10] * FE9_C1_D010_Qfad[0][0][0][3];
    const double J_c8 = coordinate_dofs[2] * FE9_C2_D001_Qfad[0][0][0][0] + coordinate_dofs[5] * FE9_C2_D001_Qfad[0][0][0][1] + coordinate_dofs[8] * FE9_C2_D001_Qfad[0][0][0][2] + coordinate_dofs[11] * FE9_C2_D001_Qfad[0][0][0][3];
    const double J_c5 = coordinate_dofs[1] * FE9_C2_D001_Qfad[0][0][0][0] + coordinate_dofs[4] * FE9_C2_D001_Qfad[0][0][0][1] + coordinate_dofs[7] * FE9_C2_D001_Qfad[0][0][0][2] + coordinate_dofs[10] * FE9_C2_D001_Qfad[0][0][0][3];
    const double J_c7 = coordinate_dofs[2] * FE9_C1_D010_Qfad[0][0][0][0] + coordinate_dofs[5] * FE9_C1_D010_Qfad[0][0][0][1] + coordinate_dofs[8] * FE9_C1_D010_Qfad[0][0][0][2] + coordinate_dofs[11] * FE9_C1_D010_Qfad[0][0][0][3];
    const double J_c1 = coordinate_dofs[0] * FE9_C1_D010_Qfad[0][0][0][0] + coordinate_dofs[3] * FE9_C1_D010_Qfad[0][0][0][1] + coordinate_dofs[6] * FE9_C1_D010_Qfad[0][0][0][2] + coordinate_dofs[9] * FE9_C1_D010_Qfad[0][0][0][3];
    const double J_c6 = coordinate_dofs[2] * FE9_C0_D100_Qfad[0][0][0][0] + coordinate_dofs[5] * FE9_C0_D100_Qfad[0][0][0][1] + coordinate_dofs[8] * FE9_C0_D100_Qfad[0][0][0][2] + coordinate_dofs[11] * FE9_C0_D100_Qfad[0][0][0][3];
    const double J_c3 = coordinate_dofs[1] * FE9_C0_D100_Qfad[0][0][0][0] + coordinate_dofs[4] * FE9_C0_D100_Qfad[0][0][0][1] + coordinate_dofs[7] * FE9_C0_D100_Qfad[0][0][0][2] + coordinate_dofs[10] * FE9_C0_D100_Qfad[0][0][0][3];
    const double J_c2 = coordinate_dofs[0] * FE9_C2_D001_Qfad[0][0][0][0] + coordinate_dofs[3] * FE9_C2_D001_Qfad[0][0][0][1] + coordinate_dofs[6] * FE9_C2_D001_Qfad[0][0][0][2] + coordinate_dofs[9] * FE9_C2_D001_Qfad[0][0][0][3];
    ufc_scalar_t sp_fad[15];
    sp_fad[0] = J_c4 * J_c8;
    sp_fad[1] = J_c5 * J_c7;
    sp_fad[2] = sp_fad[0] + -1 * sp_fad[1];
    sp_fad[3] = J_c0 * sp_fad[2];
    sp_fad[4] = J_c5 * J_c6;
    sp_fad[5] = J_c3 * J_c8;
    sp_fad[6] = sp_fad[4] + -1 * sp_fad[5];
    sp_fad[7] = J_c1 * sp_fad[6];
    sp_fad[8] = sp_fad[3] + sp_fad[7];
    sp_fad[9] = J_c3 * J_c7;
    sp_fad[10] = J_c4 * J_c6;
    sp_fad[11] = sp_fad[9] + -1 * sp_fad[10];
    sp_fad[12] = J_c2 * sp_fad[11];
    sp_fad[13] = sp_fad[8] + sp_fad[12];
    sp_fad[14] = fabs(sp_fad[13]);
    for (int iq = 0; iq < 4; ++iq)
    {
        // Quadrature loop body setup for quadrature rule fad
        // Varying computations for quadrature rule fad
        ufc_scalar_t w0 = 0.0;
        for (int ic = 0; ic < 4; ++ic)
            w0 += w[ic] * FE8_C0_Qfad[0][0][iq][ic];
        ufc_scalar_t sv_fad[1];
        sv_fad[0] = sp_fad[14] * w0;
        const ufc_scalar_t fw0 = sv_fad[0] * weights_fad[iq];
        for (int i = 0; i < 4; ++i)
            A[i] += fw0 * FE8_C0_Qfad[0][0][iq][i];
    }
}

bool enabled_coefficients_integral_e662eb318e752baadbe6a15e0a8dd3a9e542583e[1] = { false };

ufc_integral integral_e662eb318e752baadbe6a15e0a8dd3a9e542583e =
{
  .enabled_coefficients = enabled_coefficients_integral_e662eb318e752baadbe6a15e0a8dd3a9e542583e,
  .tabulate_tensor = tabulate_tensor_integral_e662eb318e752baadbe6a15e0a8dd3a9e542583e,
  .needs_transformation_data = 0
};

// End of code for integral integral_e662eb318e752baadbe6a15e0a8dd3a9e542583e

// Code for form form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb


ufc_dofmap* dofmaps_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb[2] = { &dofmap_8e2ddea2c2f726e9e0db250bec514d348ab6d807, &dofmap_8e2ddea2c2f726e9e0db250bec514d348ab6d807 };
ufc_finite_element* finite_elements_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb[2] = { &element_8e2ddea2c2f726e9e0db250bec514d348ab6d807, &element_8e2ddea2c2f726e9e0db250bec514d348ab6d807 };

// Return a list of the coefficient names.
const char** coefficient_name_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb(void)
{
return NULL;
}

// Return a list of the constant names.
const char** constant_name_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb(void)
{
return NULL;
}

int* integral_ids_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb(ufc_integral_type integral_type)
{
static int integral_ids_cell_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb[1] = { -1 };
switch (integral_type)
{
case cell:
    return integral_ids_cell_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb;
default:
    return NULL;
}
}

int num_integrals_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb(ufc_integral_type integral_type)
{
switch (integral_type)
{
case cell:
    return 1;
case interior_facet:
    return 0;
case exterior_facet:
    return 0;
default:
    return 0;
}
}

ufc_integral** integrals_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb(ufc_integral_type integral_type)
{
static ufc_integral* integrals_cell_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb[1] = { &integral_dcc557d3a90e447473a071b6b240c36c2de6fcaf };
switch (integral_type)
{
case cell:
    return integrals_cell_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb;
default:
    return NULL;
}
}

ufc_form form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb =
{

  .signature = "f926a764b806bd19d493250d1cb24c767be417cfaf5266094420bc91e30b1ab8aaa449aa65e1cc2bb5506f901f4c5c83020b9c0f1dbfb8e658b99153f701c283",
  .rank = 2,
  .num_coefficients = 0,
  .num_constants = 0,
  .original_coefficient_position = NULL,

  .coefficient_name_map = coefficient_name_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb,
  .constant_name_map = constant_name_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb,

  .finite_elements = finite_elements_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb,
  .dofmaps = dofmaps_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb,

  .integral_ids = integral_ids_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb,
  .num_integrals = num_integrals_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb,

  .integrals = integrals_form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb
};

// Alias name
ufc_form* form_problem_a = &form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb;

ufc_function_space* functionspace_form_problem_a(const char* function_name)
{
static ufc_function_space functionspace_v =
{
.finite_element = &element_8e2ddea2c2f726e9e0db250bec514d348ab6d807,
.dofmap = &dofmap_8e2ddea2c2f726e9e0db250bec514d348ab6d807,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
static ufc_function_space functionspace_u =
{
.finite_element = &element_8e2ddea2c2f726e9e0db250bec514d348ab6d807,
.dofmap = &dofmap_8e2ddea2c2f726e9e0db250bec514d348ab6d807,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
if (strcmp(function_name, "v") == 0)
    return &functionspace_v;
else if (strcmp(function_name, "u") == 0)
    return &functionspace_u;
return NULL;

}

// End of code for form form_0cd294bc48ae2e06176fbc28dfd5d379274d2afb

// Code for form form_2f88875bcad512b9bf1faed750d53225fe18ed14

int original_coefficient_position_form_2f88875bcad512b9bf1faed750d53225fe18ed14[1] = { 0 };
ufc_dofmap* dofmaps_form_2f88875bcad512b9bf1faed750d53225fe18ed14[2] = { &dofmap_8e2ddea2c2f726e9e0db250bec514d348ab6d807, &dofmap_8e2ddea2c2f726e9e0db250bec514d348ab6d807 };
ufc_finite_element* finite_elements_form_2f88875bcad512b9bf1faed750d53225fe18ed14[2] = { &element_8e2ddea2c2f726e9e0db250bec514d348ab6d807, &element_8e2ddea2c2f726e9e0db250bec514d348ab6d807 };

// Return a list of the coefficient names.
const char** coefficient_name_form_2f88875bcad512b9bf1faed750d53225fe18ed14(void)
{
static const char* names[1] = { "f" };
return names;
}

// Return a list of the constant names.
const char** constant_name_form_2f88875bcad512b9bf1faed750d53225fe18ed14(void)
{
return NULL;
}

int* integral_ids_form_2f88875bcad512b9bf1faed750d53225fe18ed14(ufc_integral_type integral_type)
{
static int integral_ids_cell_form_2f88875bcad512b9bf1faed750d53225fe18ed14[1] = { -1 };
switch (integral_type)
{
case cell:
    return integral_ids_cell_form_2f88875bcad512b9bf1faed750d53225fe18ed14;
default:
    return NULL;
}
}

int num_integrals_form_2f88875bcad512b9bf1faed750d53225fe18ed14(ufc_integral_type integral_type)
{
switch (integral_type)
{
case cell:
    return 1;
case interior_facet:
    return 0;
case exterior_facet:
    return 0;
default:
    return 0;
}
}

ufc_integral** integrals_form_2f88875bcad512b9bf1faed750d53225fe18ed14(ufc_integral_type integral_type)
{
static ufc_integral* integrals_cell_form_2f88875bcad512b9bf1faed750d53225fe18ed14[1] = { &integral_e662eb318e752baadbe6a15e0a8dd3a9e542583e };
switch (integral_type)
{
case cell:
    return integrals_cell_form_2f88875bcad512b9bf1faed750d53225fe18ed14;
default:
    return NULL;
}
}

ufc_form form_2f88875bcad512b9bf1faed750d53225fe18ed14 =
{

  .signature = "44106fd01405fbd79a786ee9e6b6ca66032a217066d9f7e89d62509a023009da7f35d5d45d512d692f78fb6870e876cb1de1a826ceb3fcbf1de7c735e46b5b08",
  .rank = 1,
  .num_coefficients = 1,
  .num_constants = 0,
  .original_coefficient_position = original_coefficient_position_form_2f88875bcad512b9bf1faed750d53225fe18ed14,

  .coefficient_name_map = coefficient_name_form_2f88875bcad512b9bf1faed750d53225fe18ed14,
  .constant_name_map = constant_name_form_2f88875bcad512b9bf1faed750d53225fe18ed14,

  .finite_elements = finite_elements_form_2f88875bcad512b9bf1faed750d53225fe18ed14,
  .dofmaps = dofmaps_form_2f88875bcad512b9bf1faed750d53225fe18ed14,

  .integral_ids = integral_ids_form_2f88875bcad512b9bf1faed750d53225fe18ed14,
  .num_integrals = num_integrals_form_2f88875bcad512b9bf1faed750d53225fe18ed14,

  .integrals = integrals_form_2f88875bcad512b9bf1faed750d53225fe18ed14
};

// Alias name
ufc_form* form_problem_L = &form_2f88875bcad512b9bf1faed750d53225fe18ed14;

ufc_function_space* functionspace_form_problem_L(const char* function_name)
{
static ufc_function_space functionspace_v =
{
.finite_element = &element_8e2ddea2c2f726e9e0db250bec514d348ab6d807,
.dofmap = &dofmap_8e2ddea2c2f726e9e0db250bec514d348ab6d807,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
static ufc_function_space functionspace_f =
{
.finite_element = &element_8e2ddea2c2f726e9e0db250bec514d348ab6d807,
.dofmap = &dofmap_8e2ddea2c2f726e9e0db250bec514d348ab6d807,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
if (strcmp(function_name, "v") == 0)
    return &functionspace_v;
else if (strcmp(function_name, "f") == 0)
    return &functionspace_f;
return NULL;

}

// End of code for form form_2f88875bcad512b9bf1faed750d53225fe18ed14
