// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCX version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': 'src/',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'sycl_defines': True,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['problem.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

ufc_finite_element* create_element_33bacbb0652e765e59ee81be7b53635d70be5fa4(void);

ufc_finite_element* create_element_4bfea52d0a8487e3588534d0f793633707ee33df(void);

ufc_finite_element* create_element_5c7ff8918798f3fa637261a8aab86c8b7befba50(void);

ufc_dofmap* create_dofmap_33bacbb0652e765e59ee81be7b53635d70be5fa4(void);

ufc_dofmap* create_dofmap_4bfea52d0a8487e3588534d0f793633707ee33df(void);

ufc_dofmap* create_dofmap_5c7ff8918798f3fa637261a8aab86c8b7befba50(void);

ufc_coordinate_mapping* create_coordinate_mapping_1e6cf0cad05c1670582161ba5e4b62549b87a508(void);

// Helper used to create coordinate map using name given to the
// UFL file.
// This helper is called in user c++ code.
//
ufc_coordinate_mapping* create_coordinate_map_problem(void);

ufc_integral* create_integral_cell_otherwise_e114f2f943e3d81da55ef77c5713336a178897aa(void);

ufc_integral* create_integral_cell_otherwise_f867d65b51dc6ed3dd2fe8ebf610e1251493c444(void);

ufc_form* create_form_e114f2f943e3d81da55ef77c5713336a178897aa(void);

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
ufc_form* create_form_problem_a(void);

// Helper used to create function space using its name, as given in
// the UFL file.
// Note: There are in general more function spaces associated to the form,
//       which is the reason why the helpers takes name as argument.
// This helper is called in user c++ code.
//
ufc_function_space* create_functionspace_form_problem_a(const char* fs_name);


ufc_form* create_form_f867d65b51dc6ed3dd2fe8ebf610e1251493c444(void);

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
ufc_form* create_form_problem_L(void);

// Helper used to create function space using its name, as given in
// the UFL file.
// Note: There are in general more function spaces associated to the form,
//       which is the reason why the helpers takes name as argument.
// This helper is called in user c++ code.
//
ufc_function_space* create_functionspace_form_problem_L(const char* fs_name);


#ifdef __cplusplus
}
#endif
